#pragma once
// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.
constexpr const char* CONFIG_REVISION = "solid-manifold-openmodelica-v0.4";
constexpr const char* CONFIG_BASELINE_SHA256 = "f9db44a7393df07e8d524dda16de979aa23652ec31786cd1e87788d377a37b8f";
constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{
    1.8f, 1.35f,
    2.0f, 0.72f,
    12.0f, 18.0f,
    64.0f, 80.0f, false};
constexpr ProcessProfile PLA_PROFILE{
    MaterialProfile::PLA, 32, 11.0f, 18.0f,
    650, 800, 3, 45, false, 0, 0,
    2.2f, 18.0f,
    {180, 195, 205}, 200, 65,
    18.6f, 0.4f, 0.025f, 80};
constexpr ProcessProfile PET_PROFILE{
    MaterialProfile::PET, 24, 13.0f, 18.0f,
    850, 1100, 3, 60, false, 0, 0,
    1.8f, 20.0f,
    {245, 260, 270}, 265, 85,
    16.7f, 0.3f, 0.018f, 120};
constexpr float INPUT_MECHANICAL_FUSE_NM = 22.0f;
constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = 34.0f;
constexpr float SHAFT_CUTTER_ALLOWABLE_NM = 48.0f;
