#pragma once
// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.
constexpr const char* CONFIG_REVISION = "coupled-digital-validation-v0.5";
constexpr const char* CONFIG_BASELINE_SHA256 = "7a602451aee906b2118e28861738dfaa0bfa16c44baf52183100004cb80a1013";
constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{
    0.75f, 1.316f,
    2.5f, 0.85f,
    8.2f, 20.0f,
    95.0f, 80.0f, false};
constexpr ProcessProfile PLA_PROFILE{
    MaterialProfile::PLA, 32, 11.0f, 18.0f,
    650, 800, 3, 45, false, 0, 0,
    2.2f, 18.0f,
    {180, 195, 205}, 200, 65,
    18.6f, 0.4f, 0.025f, 80};
constexpr ProcessProfile PET_PROFILE{
    MaterialProfile::PET, 24, 13.0f, 18.0f,
    850, 1100, 3, 60, false, 0, 0,
    1.8f, 20.0f,
    {245, 260, 270}, 265, 85,
    16.7f, 0.3f, 0.018f, 120};
constexpr float INPUT_MECHANICAL_FUSE_NM = 22.0f;
constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = 34.0f;
constexpr float SHAFT_CUTTER_ALLOWABLE_NM = 48.0f;
