#pragma once
// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.
constexpr const char* CONFIG_REVISION = "virtual-physics-closure-v0.5.1";
constexpr const char* CONFIG_BASELINE_SHA256 = "28532bb5439a1749c34e643f173d18d13bacd882b99b4bd557e0357ba92956b0";
constexpr const char* PROCESS_CONTRACT_SHA256 = "98c5186e0b0a8083768ba63d240d5287e7e2a07723ddd23874e411bdf5bc65c4";
enum class MachineState : uint8_t { IDLE, SHREDDING, PREHEATING, EXTRUSION, COOLDOWN, FAULT, ESTOP };
struct StatePermissions { bool shredder, screw, process_heaters, feeder, puller, spooler, cooling; };
struct PhasePower { float average_w, peak_w; };
constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{
    0.75f, 1.316f,
    2.5f, 0.85f,
    8.2f, 20.0f,
    95.0f, 80.0f, false};
constexpr ProcessProfile PLA_PROFILE{
    MaterialProfile::PLA, 32, 11.0f, 18.0f,
    650, 800, 3, 45, false, 0, 0,
    2.2f, 16.0f,
    {180, 195, 205}, 200, 100,
    9.28f, 0.4f, 0.025f, 80};
constexpr ProcessProfile PET_PROFILE{
    MaterialProfile::PET, 24, 13.0f, 18.0f,
    850, 1100, 3, 60, false, 0, 0,
    1.8f, 18.0f,
    {245, 260, 270}, 265, 100,
    8.66f, 0.3f, 0.018f, 120};
constexpr float INPUT_MECHANICAL_FUSE_NM = 22.0f;
constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = 34.0f;
constexpr float SHAFT_CUTTER_ALLOWABLE_NM = 48.0f;
constexpr uint16_t JAM_STARTUP_GRACE_MS = 3000;
constexpr float JAM_RPM_DEFICIT_RATIO = 0.65f;
constexpr float JAM_CURRENT_SENSOR_SATURATION_A = 6.4f;
constexpr uint16_t JAM_STOP_MS = 250;
constexpr float PLA_SHREDDER_DUTY_BIAS = 0.1f;
constexpr float PLA_SHREDDER_SPEED_KP = 0.08f;
constexpr float PET_SHREDDER_DUTY_BIAS = 0.115f;
constexpr float PET_SHREDDER_SPEED_KP = 0.06f;
constexpr float NORMAL_PHASE_PEAK_LIMIT_W = 500.0f;
constexpr float PSU_RATING_W = 600.0f;
constexpr StatePermissions STATE_PERMISSIONS[] = {
    {false, false, false, false, false, false, false}, // IDLE
    {true, false, false, false, false, false, false}, // SHREDDING
    {false, false, true, false, false, false, true}, // PREHEATING
    {false, true, true, true, true, true, true}, // EXTRUSION
    {false, false, false, false, false, false, true}, // COOLDOWN
    {false, false, false, false, false, false, true}, // FAULT
    {false, false, false, false, false, false, false}, // ESTOP
};
constexpr PhasePower NORMAL_PHASE_POWER[] = {
    {310.0f, 477.0f}, // SHREDDING
    {300.0f, 405.0f}, // PREHEATING
    {340.0f, 490.0f}, // EXTRUSION
    {36.0f, 61.0f}, // COOLDOWN
};
