model SequenceDemand
  "Sizing demand experiment; not a validated controller or rheological solver"
  constant Real pi=3.141592653589793;
  parameter Integer material=1;
  parameter Integer fault=0 "0 normal, 1 cutter jam, 2 blocked die, 3 starvation";
  parameter Real throughputGph=100;
  parameter Real deliveryGphPerRpm=6.209;
  parameter Real shredRpm=16;
  parameter Real shearMPa=35;
  parameter Real effectiveCutAreaMM2=8 "Sum of concurrent cut areas over both shafts";
  parameter Real cutterRadiusMM=29;
  parameter Real cuttingGeometryFactor=1.2;
  parameter Real pressureMPa=3 "Uncalibrated normal-process sensitivity, not inferred pressure";
  parameter Real viscosityPaS=1000 "Apparent viscosity sensitivity, not lot measurement";
  parameter Real conveyingEfficiency=0.4 "Pressure-to-shaft work screening assumption";
  parameter Real solidFeedTorqueNm=0.8;
  parameter Real screwDiameterM=0.016;
  parameter Real barrelBoreM=0.01622;
  parameter Real screwPitchM=0.016;
  parameter Real meteringDepthM=0.00096;
  parameter Real activeMeltLengthM=0.160;
  parameter Real flightWidthM=0.0015;
  parameter Real tipClearanceM=0.00015;
  parameter Real dieDiameterM=0.003;
  parameter Real dieLengthM=0.010;
  Real tempC(start=25,fixed=true);
  Real tempTarget;
  Real heaterW;
  discrete Real readyAt(start=-1,fixed=true);
  Boolean ready;
  Boolean shredding;
  Boolean extruding;
  Boolean purging;
  Boolean blocked;
  Integer stage;
  Real theta(start=0,fixed=true);
  Real shredOmega;
  Real screwOmega;
  Real pulse;
  Real cutPeakNm;
  Real shredTorqueNm;
  Real screwTorqueNm;
  Real viscousTorqueNm;
  Real pressureTorqueNm;
  Real hydraulicLowerTorqueNm;
  Real diePressurePa;
  Real effectiveViscosity;
  Real flowGph;
  Real accumulatedG(start=0,fixed=true);
  Real energyJ(start=0,fixed=true);
  Real shSquare(start=0,fixed=true);
  Real exSquare(start=0,fixed=true);
  Real shTime(start=0,fixed=true);
  Real exTime(start=0,fixed=true);
  Real shPeak;
  Real exPeak;
  Real frictionNm;
  Real shaftPowerW;
  Real processTime;
  Real density=if material==1 then 1150 else 1250;
equation
  tempTarget=if material==1 then 205 else 270;
  heaterW=if time<140 or time>=1500 then 0 else min(360,max(0,4*(tempTarget-tempC)+0.75*(tempTarget-25)));
  500*der(tempC)=heaterW-0.75*(tempC-25)-flowGph/3.6e6*1600*max(0,tempC-25);
  ready=tempC>=tempTarget-3 and time>=140;
  when ready and pre(readyAt)<0 then readyAt=time; end when;
  processTime=if readyAt>=0 then time-readyAt else -1;
  blocked=fault==2 and processTime>=90;
  shredding=time>=5 and time<125;
  extruding=readyAt>=0 and processTime>=30 and time<1450 and not blocked;
  purging=extruding and time>=1400;
  stage=if shredding then 1 else if extruding then (if purging then 4 else 3) else if time>=1500 then 5 else 2;
  shredOmega=if shredding and not (fault==1 and time>=65 and time<66) then shredRpm*pi/30 else 0;
  der(theta)=shredOmega;
  pulse=max(0,sin(7*theta))^4;
  cutPeakNm=shearMPa*effectiveCutAreaMM2*cutterRadiusMM/1000*cuttingGeometryFactor;
  shredTorqueNm=if not shredding then 0 else if fault==1 and time>=65 and time<66 then 0 else 0.6+cutPeakNm*pulse;
  screwOmega=if extruding then throughputGph/deliveryGphPerRpm*pi/30*(if purging then 1.1 else 1) else 0;
  flowGph=if extruding then screwOmega*30/pi*deliveryGphPerRpm*(if fault==3 and mod(processTime,40)<10 then 0.5 else 1) else 0;
  effectiveViscosity=viscosityPaS*exp(5000*(1/(tempC+273.15)-1/(tempTarget+273.15)));
  viscousTorqueNm=2*pi*effectiveViscosity*screwOmega*(screwDiameterM/2)^3*activeMeltLengthM*((1-flightWidthM/screwPitchM)/meteringDepthM+(flightWidthM/screwPitchM)/tipClearanceM);
  pressureTorqueNm=if extruding then pressureMPa*1e6*pi*barrelBoreM^2/4*screwPitchM/(2*pi*conveyingEfficiency) else 0;
  diePressurePa=128*effectiveViscosity*dieLengthM*(flowGph/3.6e6/density)/(pi*dieDiameterM^4);
  hydraulicLowerTorqueNm=diePressurePa*(flowGph/3.6e6/density)/max(1e-9,screwOmega);
  frictionNm=if extruding then 0.2+solidFeedTorqueNm*(if purging then 1.3 else 1) else 0;
  screwTorqueNm=viscousTorqueNm+pressureTorqueNm+frictionNm;
  shaftPowerW=abs(shredTorqueNm*shredOmega)+abs(screwTorqueNm*screwOmega);
  der(accumulatedG)=flowGph/3600;
  der(energyJ)=shaftPowerW;
  der(shSquare)=shredTorqueNm^2;
  der(exSquare)=if extruding and not purging then screwTorqueNm^2 else 0;
  der(shTime)=if shredding then 1 else 0;
  der(exTime)=if extruding and not purging then 1 else 0;
  shPeak=0.6+cutPeakNm;
  exPeak=screwTorqueNm;
  assert(not (shredding and extruding),"Independent process phases must not overlap");
  assert(not extruding or tempC>=tempTarget-5,"No extrusion of a cold charge");
  assert(not blocked or abs(screwOmega)<1e-9,"Blocked-die scenario must request stop");
  annotation(experiment(StopTime=1800,Tolerance=1e-7,Interval=0.02));
end SequenceDemand;
