within PLA_PET_Recycler.Systems;
model ActuationShadowSystem
  parameter Real targetLineSpeed=9.28 "mm/s";
  parameter Real pullerLoadFactor=1.0;
  parameter Real pullerFaultStart=1e9;
  parameter Real pullerFaultEnd=1e9;
  parameter Boolean pullerTachAvailable=true;
  parameter Boolean fan1Available=true;
  parameter Boolean fan2Available=true;
  parameter Boolean coolingFeedbackWhileOff=false;
  parameter Real ductFlowFactor=1.0;
  parameter Real screwMotionRatio=1.0;
  parameter Real purgeDuration=130.0;
  parameter Real heaterRequestPercent=100.0;
  parameter Real heaterCapW=300.0;
  parameter Real spoolFill=0.0;
  parameter Boolean spoolJam=false;
  parameter Boolean traverseLimitHealthy=true;
  parameter Boolean gaugeValid=true;
  parameter Boolean operatorRethread=true;
  parameter Real requalificationStart=5.0;
  Real pullerSpeed(start=0,fixed=true) "mm/s";
  Real pullerCommand;
  Real pullerError;
  Real pullerIntegrator(start=0,fixed=true);
  Boolean pullerLimited;
  Boolean pullerSaturated;
  Boolean pullerTachValid;
  Real fan1Rpm;
  Real fan2Rpm;
  Boolean coolingValid;
  Real inferredAirflowM3H;
  Real screwCommandRpm;
  Real screwActualRpm;
  Real measuredPurgeRevolutions(start=0,fixed=true);
  Boolean screwMotionMismatch;
  Boolean purgeComplete;
  Real heaterRequestedPowerW;
  Real heaterAllocatedPowerW;
  Real heaterAllocationScale;
  Real heaterIntegrator(start=0,fixed=true);
  Real spoolRadiusMm;
  Real spoolTargetRpm;
  Real spoolActualRpm;
  Real dancerAngle(start=0,fixed=true);
  Boolean spoolJamDetected;
  Real spoolTurns(start=0,fixed=true);
  Real traversePositionMm;
  Boolean traverseHardFault;
  Boolean formingFault;
  Boolean feederEnabled;
  Boolean spoolEligible;
  Boolean wastePathActive;
equation
  pullerCommand=min(80,max(0,targetLineSpeed+2.8*pullerError+0.6*pullerIntegrator));
  der(pullerIntegrator)=pullerError+0.35*(pullerCommand-(targetLineSpeed+2.8*pullerError+0.6*pullerIntegrator));
  der(pullerSpeed)=((if time>=pullerFaultStart and time<pullerFaultEnd then 0 else pullerCommand/pullerLoadFactor)-pullerSpeed)/0.35;
  pullerError=targetLineSpeed-pullerSpeed;
  pullerLimited=noEvent(pullerCommand<=0.01 or pullerCommand>=79.99);
  pullerSaturated=time>=pullerFaultStart+0.8 and time<pullerFaultEnd;
  pullerTachValid=pullerTachAvailable or time<0.6;
  fan1Rpm=if fan1Available then 1800 else 0;
  fan2Rpm=if fan2Available then 1800 else 0;
  coolingValid=fan1Rpm>=300 and fan2Rpm>=300 and not coolingFeedbackWhileOff;
  inferredAirflowM3H=((if fan1Available then 18 else 0)+(if fan2Available then 18 else 0))*ductFlowFactor;
  screwCommandRpm=16;
  screwActualRpm=screwCommandRpm*screwMotionRatio;
  der(measuredPurgeRevolutions)=if time<=purgeDuration then screwActualRpm/60 else 0;
  screwMotionMismatch=time>=1.5 and screwActualRpm<0.35*screwCommandRpm;
  purgeComplete=time>=120 and measuredPurgeRevolutions>=32 and not screwMotionMismatch;
  heaterRequestedPowerW=3*100*heaterRequestPercent/100+60*heaterRequestPercent/100;
  heaterAllocatedPowerW=min(heaterCapW,heaterRequestedPowerW);
  heaterAllocationScale=if heaterRequestedPowerW>0 then heaterAllocatedPowerW/heaterRequestedPowerW else 1;
  der(heaterIntegrator)=25+0.35*(100*heaterAllocationScale-heaterRequestPercent)-heaterIntegrator/20;
  spoolRadiusMm=26+(100-26)*spoolFill;
  spoolTargetRpm=targetLineSpeed*60/(2*Modelica.Constants.pi*spoolRadiusMm);
  spoolActualRpm=if spoolJam then 0 else spoolTargetRpm;
  der(dancerAngle)=if spoolJam and time<1.0 then 0.12 else -dancerAngle/0.5;
  spoolJamDetected=spoolJam and time>=1.0;
  der(spoolTurns)=spoolActualRpm/60;
  traversePositionMm=abs(mod(spoolTurns*1.85,136)-68);
  traverseHardFault=not traverseLimitHealthy and time>=1.2;
  formingFault=not gaugeValid or not coolingValid or not pullerTachValid or pullerSaturated or
      spoolJamDetected or traverseHardFault or screwMotionMismatch;
  feederEnabled=not formingFault;
  spoolEligible=not formingFault and gaugeValid and time-requalificationStart>=10 and operatorRethread;
  wastePathActive=not spoolEligible;
end ActuationShadowSystem;
