within PLA_PET_Recycler.Systems;
model CoupledShredderSystem
  parameter Integer material=1;
  parameter Integer rightMaterial=material;
  parameter Integer leftMaterial=material;
  parameter Real targetRPM=32;
  parameter Boolean enabled=true;
  parameter Real stopTime=1e9;
  parameter Real jamReleaseTime=1e9;
  parameter Real engagement=1.0;
  parameter Real overloadDwell=0.65;
  parameter Real currentThreshold=8.2;
  Components.DCMotorElectrical motor;
  Components.LossyGearbox gearbox(ratio=47,efficiency=0.71);
  Components.ShearFuse inputFuse(tripTorque=10.35);
  Components.ElasticChainDrive chain(ratio=2.5,efficiency=0.85);
  Modelica.Mechanics.Rotational.Components.Inertia rightRotor(J=Generated.CADParameters.cutterRotorJ,phi(start=0,fixed=true),w(start=0,fixed=true));
  Modelica.Mechanics.Rotational.Components.Inertia leftRotor(J=Generated.CADParameters.cutterRotorJ,phi(start=0,fixed=true),w(start=0,fixed=true));
  Components.PhaseGearMesh phase;
  Components.HookMaterialLoad rightLoad(material=rightMaterial,engagement=engagement,releaseTime=jamReleaseTime);
  Components.HookMaterialLoad leftLoad(material=leftMaterial,engagement=engagement,releaseTime=jamReleaseTime,phaseOffset=Modelica.Constants.pi/7);
  Real cutterRPM;
  Real targetOmega;
  Real speedError;
  Real voltageFeedForward;
  Real rawDuty;
  Real dutyState(start=0,fixed=true);
  Real dutyCommand;
  Real overloadTimer(start=0,fixed=true);
  Real faultTimer(start=0,fixed=true);
  discrete Boolean jamLatched(start=false,fixed=true);
  Boolean overloadCondition;
  Boolean jamDetected;
  Boolean normalStop;
  Boolean jamFault;
  Real estimatedCutterTorque;
  Real bearingLoad;
equation
  connect(motor.shaft,gearbox.motorSide);
  connect(gearbox.outputSide,inputFuse.driveSide);
  connect(inputFuse.loadSide,chain.motorSprocket);
  connect(chain.cutterSprocket,rightRotor.flange_a);
  connect(rightRotor.flange_b,phase.rightShaft);
  connect(rightRotor.flange_b,rightLoad.shaft);
  connect(phase.leftShaft,leftRotor.flange_a);
  connect(leftRotor.flange_b,leftLoad.shaft);
  cutterRPM=rightRotor.w*60/(2*Modelica.Constants.pi);
  targetOmega=targetRPM*2*Modelica.Constants.pi/60;
  speedError=targetOmega-rightRotor.w;
  voltageFeedForward=motor.backEmfConstant*targetOmega*gearbox.ratio*chain.ratio/motor.supplyVoltage;
  overloadCondition=abs(motor.current)>=currentThreshold and abs(rightRotor.w)<0.65*targetOmega and time<jamReleaseTime;
  der(overloadTimer)=if overloadCondition then 1 else -overloadTimer/0.05;
  when overloadTimer>=overloadDwell then
    jamLatched=true;
  elsewhen time>=jamReleaseTime+0.20 then
    jamLatched=false;
  end when;
  jamDetected=jamLatched;
  der(faultTimer)=if jamDetected or overloadCondition then 1 else -faultTimer/2.0;
  jamFault=faultTimer>=1.20 or inputFuse.broken;
  normalStop=(not enabled or time>=stopTime) and not jamFault;
  rawDuty=if not enabled or time>=stopTime or jamFault then 0 else if jamDetected then -0.12 else max(0,min(0.90,voltageFeedForward+0.02*speedError-0.035*(abs(motor.current)-5.0)));
  der(dutyState)=(rawDuty-dutyState)/(if jamDetected then 0.05 else 0.50);
  dutyCommand=if not enabled or time>=stopTime or jamFault then 0 else dutyState;
  motor.duty=dutyCommand;
  motor.enable=enabled and time<stopTime and not jamFault;
  estimatedCutterTorque=abs(chain.transmittedTorque);
  bearingLoad=abs(chain.tightSideForce)+phase.separatingForce+(rightLoad.loadTorque+leftLoad.loadTorque)/(2*0.029);
end CoupledShredderSystem;
