within PLA_PET_Recycler.Systems;
model CoupledShredderSystem
  parameter Integer material=1;
  parameter Integer rightMaterial=material;
  parameter Integer leftMaterial=material;
  parameter Real targetRPM=32;
  parameter Boolean enabled=true;
  parameter Boolean useExternalEnable=false;
  input Boolean externalEnable=false;
  Boolean enableCommand;
  parameter Real stopTime=1e9;
  parameter Real jamReleaseTime=1e9;
  parameter Real engagement=1.0;
  parameter Real engagementAfter=engagement;
  parameter Real engagementStepTime=1e9;
  parameter Real jamLoadTorque=20.0;
  parameter Real overloadDwell=if material==2 then 0.85 else 0.65;
  parameter Real reverseDuration=if material==2 then 1.10 else 0.80;
  parameter Integer maximumRetries=GeneratedControl.maximumRetries;
  Components.DCMotorElectrical motor;
  Components.LossyGearbox gearbox(ratio=47,efficiency=0.71);
  Components.ShearFuse inputFuse(tripTorque=10.35);
  Components.ElasticChainDrive chain(ratio=2.5,efficiency=0.85);
  Modelica.Mechanics.Rotational.Components.Inertia rightRotor(J=Generated.CADParameters.cutterRotorJ,phi(start=0,fixed=true),w(start=0,fixed=true));
  Modelica.Mechanics.Rotational.Components.Inertia leftRotor(J=Generated.CADParameters.cutterRotorJ,phi(start=0,fixed=true),w(start=0,fixed=true));
  Components.PhaseGearMesh phase;
  Components.HookMaterialLoad rightLoad(material=rightMaterial,engagement=engagement,engagementAfter=engagementAfter,engagementStepTime=engagementStepTime,jamTorque=jamLoadTorque,releaseTime=jamReleaseTime);
  Components.HookMaterialLoad leftLoad(material=leftMaterial,engagement=engagement,engagementAfter=engagementAfter,engagementStepTime=engagementStepTime,jamTorque=jamLoadTorque,releaseTime=jamReleaseTime,phaseOffset=Modelica.Constants.pi/7,forwardDirection=-1);
  Real cutterRPM;
  Real filteredCutterRPM(start=0,fixed=true);
  Real targetOmega;
  Real speedError;
  Real voltageFeedForward;
  Real rawDuty;
  Real dutyState(start=0,fixed=true);
  Real dutyCommand;
  Real overloadTimer(start=0,fixed=true);
  discrete Integer retryState(start=1,fixed=true) "1 FORWARD, 2 STOP, 3 REVERSE, 4 FAULT_LATCHED";
  discrete Integer retryCount(start=0,fixed=true);
  discrete Real stateStart(start=0,fixed=true);
  discrete Real forwardStart(start=0,fixed=true);
  Boolean overloadCondition;
  Boolean torqueOverload;
  Boolean currentSensorSaturated;
  Boolean rpmDeficit;
  Boolean startupGraceElapsed;
  Boolean jamDetected;
  Boolean normalStop;
  Boolean jamFault;
  Real estimatedCutterTorque;
  Real calibratedCutterTorque;
  Real bearingLoad;
equation
  enableCommand=if useExternalEnable then externalEnable else enabled;
  connect(motor.shaft,gearbox.motorSide);
  connect(gearbox.outputSide,inputFuse.driveSide);
  connect(inputFuse.loadSide,chain.motorSprocket);
  connect(chain.cutterSprocket,rightRotor.flange_a);
  connect(rightRotor.flange_b,phase.rightShaft);
  connect(rightRotor.flange_b,rightLoad.shaft);
  connect(phase.leftShaft,leftRotor.flange_a);
  connect(leftRotor.flange_b,leftLoad.shaft);
  cutterRPM=rightRotor.w*60/(2*Modelica.Constants.pi);
  der(filteredCutterRPM)=(cutterRPM-filteredCutterRPM)/GeneratedControl.shredderMeasurementFilter;
  targetOmega=targetRPM*2*Modelica.Constants.pi/60;
  speedError=targetOmega-filteredCutterRPM*2*Modelica.Constants.pi/60;
  voltageFeedForward=motor.backEmfConstant*targetOmega*gearbox.ratio*chain.ratio/motor.supplyVoltage;
  calibratedCutterTorque=max(0,abs(motor.current)-GeneratedControl.driveNoLoadCurrent)*GeneratedControl.driveTorquePerAmp*GeneratedControl.driveMotorToCutterRatio*GeneratedControl.driveEfficiency;
  torqueOverload=calibratedCutterTorque>=GeneratedControl.jamTripTorque;
  currentSensorSaturated=abs(motor.current)>=GeneratedControl.jamCurrentSensorSaturation;
  rpmDeficit=abs(cutterRPM)<GeneratedControl.jamRPMDeficitRatio*targetRPM;
  startupGraceElapsed=time-pre(forwardStart)>=GeneratedControl.jamStartupGrace;
  overloadCondition=startupGraceElapsed and (torqueOverload or (currentSensorSaturated and rpmDeficit)) and time<jamReleaseTime;
  der(overloadTimer)=if overloadCondition then 1 else -overloadTimer/0.05;
  when overloadTimer>=overloadDwell and pre(retryState)==1 then
    retryState=2;
    retryCount=pre(retryCount);
    stateStart=time;
    forwardStart=pre(forwardStart);
    reinit(overloadTimer,0);
  elsewhen pre(retryState)==2 and time-pre(stateStart)>=0.25 then
    retryState=3;
    retryCount=pre(retryCount)+1;
    stateStart=time;
    forwardStart=pre(forwardStart);
    reinit(overloadTimer,0);
  elsewhen pre(retryState)==3 and time-pre(stateStart)>=reverseDuration then
    retryState=if pre(retryCount)>=maximumRetries then 4 else 1;
    retryCount=pre(retryCount);
    forwardStart=time;
    stateStart=time;
    reinit(overloadTimer,0);
  elsewhen pre(retryState)==1 and pre(retryCount)>0 and not overloadCondition and time-pre(forwardStart)>=GeneratedControl.jamStartupGrace+2 then
    retryState=pre(retryState);
    retryCount=0;
    stateStart=pre(stateStart);
    forwardStart=pre(forwardStart);
    reinit(overloadTimer,0);
  end when;
  jamDetected=retryState==2 or retryState==3 or retryState==4;
  jamFault=retryState==4 or inputFuse.broken;
  normalStop=(not enableCommand or time>=stopTime) and not jamFault;
  rawDuty=if not enableCommand or time>=stopTime or jamFault or retryState==2 then 0 else if retryState==3 then -0.12 else max(0,min(GeneratedControl.shredderDutyLimit,voltageFeedForward+GeneratedControl.shredderDutyBiasByMaterial[if material==2 then 2 else 1]+GeneratedControl.shredderSpeedKpByMaterial[if material==2 then 2 else 1]*speedError));
  der(dutyState)=(rawDuty-dutyState)/(if retryState==2 or retryState==3 then 0.05 else GeneratedControl.shredderCommandFilter);
  dutyCommand=if not enableCommand or time>=stopTime or jamFault then 0 else dutyState;
  motor.duty=dutyCommand;
  motor.enable=enableCommand and time<stopTime and not jamFault;
  estimatedCutterTorque=abs(chain.transmittedTorque);
  bearingLoad=abs(chain.tightSideForce)+phase.separatingForce+(rightLoad.loadTorque+leftLoad.loadTorque)/(2*0.029);
end CoupledShredderSystem;
