within PLA_PET_Recycler.Systems;
model DynamicSpoolSystem
  parameter Real lineSpeedCommand=0.020 "m/s";
  parameter Boolean useExternalLineSpeed=false;
  input Real externalLineSpeed=0;
  parameter Boolean useExternalEnable=false;
  input Boolean externalEnable=true;
  input Boolean externalDemand=true;
  parameter Real initialFill=0 "0 empty, 0.5 half, 1 full";
  parameter Boolean spoolJammed=false;
  parameter Boolean gaugeValid=true;
  parameter Boolean useExternalGaugeValid=false;
  input Boolean externalGaugeValid=true;
  parameter Real traverseDisturbance=0.0;
  parameter Real coreRadius=0.052;
  parameter Real fullRadius=0.100;
  parameter Real windingWidth=0.073;
  parameter Real fillFactor=0.88;
  parameter Real filamentDiameter=1.75e-3;
  Real spoolAngle(start=0,fixed=true);
  Real spoolSpeed(start=0,fixed=true);
  Real dancerAngle(start=0,fixed=true);
  Real dancerSpeed(start=0,fixed=true);
  Real fillFraction(start=initialFill,fixed=true);
  Real deliveredLength(start=0,fixed=true);
  Real woundLength(start=0,fixed=true);
  Real spoolRadius;
  Real spoolInertia;
  Real lineTension;
  Real lineSlack;
  Real lineLengthImbalance;
  Real effectiveLineSpeed;
  Real commandedLineSpeed;
  Real motorTorque;
  Real motorCurrent;
  Real brakeTorque;
  Real hardStopDeflection;
  Real hardStopReactionTorque;
  Real surfaceSpeed;
  Real speedError;
  Real filamentArea;
  Boolean dancerWarning;
  Boolean dancerControlledStop;
  Boolean dancerHardStop;
  Boolean dancerLimit;
  Boolean tensionFault;
  Boolean jamDetected;
  Boolean safePause;
  Boolean actuatorEnabled;
  Boolean effectiveGaugeValid;
equation
  filamentArea=Modelica.Constants.pi*(filamentDiameter/2)^2;
  spoolRadius=sqrt(coreRadius^2+fillFraction*(fullRadius^2-coreRadius^2));
  spoolInertia=Generated.CADParameters.spoolEmptyJ+(Generated.CADParameters.spoolFullJ-Generated.CADParameters.spoolEmptyJ)*fillFraction;
  surfaceSpeed=spoolSpeed*spoolRadius;
  lineLengthImbalance=deliveredLength-woundLength-0.20*dancerAngle;
  commandedLineSpeed=if useExternalLineSpeed then externalLineSpeed else lineSpeedCommand;
  actuatorEnabled=if useExternalEnable then externalEnable else true;
  effectiveGaugeValid=if useExternalGaugeValid then externalGaugeValid else gaugeValid;
  effectiveLineSpeed=if safePause then 0 else commandedLineSpeed;
  der(deliveredLength)=effectiveLineSpeed;
  der(woundLength)=max(0,surfaceSpeed);
  speedError=effectiveLineSpeed-surfaceSpeed+0.8*lineLengthImbalance;
  motorTorque=if safePause or not effectiveGaugeValid or not actuatorEnabled then 0 else max(-0.45,min(0.45,6.0*speedError+0.20*dancerAngle));
  motorCurrent=abs(motorTorque)/0.12+0.15;
  brakeTorque=if spoolJammed then max(-8,min(8,1200*spoolSpeed+20*spoolAngle)) else 0;
  lineTension=max(0,1.2+220*(surfaceSpeed-effectiveLineSpeed)-12*dancerAngle+traverseDisturbance);
  lineSlack=max(0,lineLengthImbalance);
  spoolInertia*der(spoolSpeed)=motorTorque-lineTension*spoolRadius-0.002*spoolSpeed-brakeTorque;
  der(spoolAngle)=spoolSpeed;
  hardStopDeflection=max(0,abs(dancerAngle)-GeneratedControl.dancerHardStop);
  hardStopReactionTorque=if hardStopDeflection > 0 then sign(dancerAngle)*(GeneratedControl.dancerHardStopStiffness*hardStopDeflection+GeneratedControl.dancerHardStopDamping*max(0,sign(dancerAngle)*dancerSpeed)) else 0;
  0.006*der(dancerSpeed)=lineLengthImbalance*14+lineTension*0.10-0.30*dancerAngle-0.025*dancerSpeed-hardStopReactionTorque;
  der(dancerAngle)=dancerSpeed;
  der(fillFraction)=if initialFill>=1 then 0 else filamentArea*max(0,surfaceSpeed)/(Modelica.Constants.pi*(fullRadius^2-coreRadius^2)*windingWidth*fillFactor);
  dancerWarning=abs(dancerAngle)>=GeneratedControl.dancerWarning;
  dancerControlledStop=abs(dancerAngle)>=GeneratedControl.dancerControlledStop;
  dancerHardStop=abs(dancerAngle)>=GeneratedControl.dancerHardStop;
  dancerLimit=dancerHardStop;
  jamDetected=spoolJammed and (abs(spoolSpeed)<0.02 or lineSlack>0.015);
  tensionFault=lineTension>8 or dancerControlledStop or lineSlack>0.035 or not effectiveGaugeValid;
  safePause=tensionFault or (useExternalEnable and externalDemand and not actuatorEnabled);
end DynamicSpoolSystem;
