within PLA_PET_Recycler.Systems;
model FilamentFormingSystem
  parameter Integer material=1 "1 PLA, 2 PET";
  parameter Real fanPercent=100;
  parameter Boolean gaugeValid=true;
  parameter Real flowStepTime=1e9;
  parameter Real flowStepFraction=0;
  parameter Real pullerDisturbanceTime=1e9;
  parameter Real pullerDisturbanceFraction=0;
  Real massFlowGPH;
  Real dieOutletTemperature;
  Boolean enabled;
  Real density;
  Real targetArea;
  Real effectiveMassFlowGPH;
  Real targetLineVelocity;
  Real pullerCommand;
  Real pullerVelocity(start=0,fixed=true);
  Real drawRatio;
  Real coolingResidenceTime;
  Real convectionCoefficient;
  Real surfaceTemperature;
  Real meanTemperature;
  Real predictedDiameter;
  Real diameterError;
  Real theoreticalDiameter;
  Real controlMargin;
  Boolean ovalityRisk;
  Boolean virtualDiameterPass;
  Boolean safePause;
equation
  density=if material==1 then 1240 else 1380;
  targetArea=Modelica.Constants.pi*(1.75e-3/2)^2;
  effectiveMassFlowGPH=massFlowGPH*(1+(if time>=flowStepTime then flowStepFraction else 0));
  targetLineVelocity=max(0,effectiveMassFlowGPH/1000/3600/(density*targetArea));
  safePause=not gaugeValid;
  pullerCommand=if enabled and not safePause then max(0,min(0.08,targetLineVelocity*(1+(if time>=pullerDisturbanceTime then pullerDisturbanceFraction else 0)))) else 0;
  der(pullerVelocity)=(pullerCommand-pullerVelocity)/0.8;
  theoreticalDiameter=if effectiveMassFlowGPH<=1e-6 or pullerVelocity<=1e-6 then 1.75 else 1000*sqrt(4*(effectiveMassFlowGPH/1000/3600)/(Modelica.Constants.pi*density*pullerVelocity));
  predictedDiameter=theoreticalDiameter;
  diameterError=predictedDiameter-1.75;
  drawRatio=if targetLineVelocity<=1e-6 then 1 else pullerVelocity/targetLineVelocity;
  coolingResidenceTime=0.323/max(1e-4,pullerVelocity);
  convectionCoefficient=20+0.45*fanPercent;
  surfaceTemperature=25+(dieOutletTemperature-25)*exp(-coolingResidenceTime/(density*1200*1.75e-3/(4*1.7*convectionCoefficient)));
  meanTemperature=25+(dieOutletTemperature-25)*exp(-coolingResidenceTime/(density*(if material==1 then 1800 else 1200)*1.75e-3/(4*convectionCoefficient)));
  ovalityRisk=meanTemperature>(if material==1 then 48 else 65) or abs(diameterError)>0.05;
  virtualDiameterPass=enabled and not safePause and abs(diameterError)<=0.05 and not ovalityRisk;
  controlMargin=0.08-pullerCommand;
end FilamentFormingSystem;
