within PLA_PET_Recycler.Systems;
model FullCoupledSystem
  parameter Integer material=1;
  parameter Integer processState=GeneratedControl.EXTRUSION;
  parameter Boolean gaugeValid=true;
  parameter Real gaugeFailureTime=1e9;
  parameter Real feederLossTime=1e9;
  parameter Real coolingLossTime=1e9;
  parameter Real spoolerPermissionLossTime=1e9;
  parameter Boolean forceJam=false;
  parameter Boolean emergencyStop=false;
  parameter Boolean guardChainOK=true;
  Boolean shredderEnabled;
  Boolean screwEnabled;
  Boolean processHeaterEnabled;
  Boolean coolingEnabled;
  Boolean effectiveGaugeValid;
  Boolean controlledPauseActive;
  Real screwScale;
  Real residualMeltState;
  CoupledShredderSystem shredder(material=if forceJam then 4 else material,useExternalEnable=true,externalEnable=shredderEnabled);
  ThermalExtruderSystem extruder(material=material,useExternalCommands=true,externalHeaterCommand=processHeaterEnabled,externalScrewCommand=screwEnabled,externalFeederCommand=feederEnable,externalScrewScale=screwScale,externalSafeHold=controlledPauseActive,screwJammed=forceJam and processState==GeneratedControl.EXTRUSION);
  FilamentFormingSystem forming(material=material,fanPercent=100,useExternalPermissions=true,externalCoolingEnabled=coolingEnabled,externalGaugeValid=effectiveGaugeValid and not emergencyStop);
  DynamicSpoolSystem spool(useExternalGaugeValid=true,externalGaugeValid=effectiveGaugeValid and not emergencyStop,spoolJammed=forceJam and processState==GeneratedControl.EXTRUSION,useExternalLineSpeed=true,externalLineSpeed=forming.pullerVelocity,useExternalEnable=true,externalEnable=spoolerEnable,externalDemand=GeneratedControl.permissions[processState,6]);
  Real busPower;
  Boolean feederEnable;
  Boolean pullerEnable;
  Boolean spoolerEnable;
  Boolean shredderDriveSafe;
  Boolean screwDriveSafe;
  Boolean heaterSafe;
  Boolean feederSafe;
  Boolean pullerSafe;
  Boolean spoolerSafe;
  Boolean powerBudgetSafe;
  Boolean mechanicalFuseStateSafe;
  Boolean restartInhibited;
  Boolean guardChainSafe;
  Boolean safeState;
equation
  effectiveGaugeValid=gaugeValid and time<gaugeFailureTime;
  controlledPauseActive=processState==GeneratedControl.EXTRUSION and not effectiveGaugeValid;
  screwScale=if controlledPauseActive then max(0,1-(time-gaugeFailureTime)/10) else 1;
  residualMeltState=extruder.feedInventoryG+0.02*max(0,extruder.Tdie-100);
  shredderEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,1];
  screwEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,2] and (effectiveGaugeValid or screwScale>0);
  processHeaterEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,3] and (effectiveGaugeValid or time<gaugeFailureTime+60);
  coolingEnabled=not emergencyStop and GeneratedControl.permissions[processState,7] and time<coolingLossTime;
  feederEnable=GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and effectiveGaugeValid and not emergencyStop and time<feederLossTime and not spool.safePause;
  pullerEnable=GeneratedControl.permissions[processState,5] and effectiveGaugeValid and not emergencyStop and not spool.safePause;
  spoolerEnable=GeneratedControl.permissions[processState,6] and effectiveGaugeValid and not emergencyStop and time<spoolerPermissionLossTime;
  forming.massFlowGPH=extruder.netFlowGPH;
  forming.dieOutletTemperature=extruder.Tdie;
  forming.enabled=pullerEnable;
  busPower=24*abs(shredder.motor.current)+0.08*24*abs(shredder.motor.current)+extruder.power1+extruder.power2+extruder.power3+extruder.powerDie+24*extruder.motorCurrent+(if feederEnable then 8 else 0)+(if pullerEnable then 12 else 0)+(if spoolerEnable then 24*spool.motorCurrent+4 else 0)+(if coolingEnabled then 16 else 0)+29;
  shredderDriveSafe=(not shredder.motor.enable or shredderEnabled) and not (shredderEnabled and (screwEnabled or processHeaterEnabled));
  screwDriveSafe=not screwEnabled or (not shredderEnabled and not extruder.driveTripped and screwScale>=0 and screwScale<=1);
  heaterSafe=(processHeaterEnabled or extruder.power1+extruder.power2+extruder.power3+extruder.powerDie<=1e-6) and not (extruder.thermalCut and extruder.power1+extruder.power2+extruder.power3+extruder.powerDie>1e-6);
  feederSafe=not feederEnable or (GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and effectiveGaugeValid and not emergencyStop);
  pullerSafe=not pullerEnable or (GeneratedControl.permissions[processState,5] and effectiveGaugeValid and not emergencyStop and not spool.safePause);
  spoolerSafe=not spoolerEnable or (GeneratedControl.permissions[processState,6] and effectiveGaugeValid and not emergencyStop);
  powerBudgetSafe=busPower<=GeneratedControl.normalPhasePeakLimit;
  mechanicalFuseStateSafe=not shredder.inputFuse.broken or not shredder.motor.enable;
  restartInhibited=not (shredder.jamFault or extruder.driveTripped or spool.safePause) or (not shredder.motor.enable and not feederEnable);
  guardChainSafe=guardChainOK or (not shredder.motor.enable and not screwEnabled and not processHeaterEnabled and not feederEnable and not pullerEnable and not spoolerEnable);
  safeState=shredderDriveSafe and screwDriveSafe and heaterSafe and feederSafe and pullerSafe and spoolerSafe and powerBudgetSafe and mechanicalFuseStateSafe and restartInhibited and guardChainSafe;
end FullCoupledSystem;
