within PLA_PET_Recycler.Systems;
model FullCoupledSystem
  parameter Integer material=1;
  parameter Integer processState=GeneratedControl.EXTRUSION;
  parameter Boolean gaugeValid=true;
  parameter Boolean forceJam=false;
  parameter Boolean emergencyStop=false;
  parameter Boolean guardChainOK=true;
  Boolean shredderEnabled;
  Boolean screwEnabled;
  Boolean processHeaterEnabled;
  Boolean coolingEnabled;
  CoupledShredderSystem shredder(material=if forceJam then 4 else material,useExternalEnable=true,externalEnable=shredderEnabled);
  ThermalExtruderSystem extruder(material=material,useExternalCommands=true,externalHeaterCommand=processHeaterEnabled,externalScrewCommand=screwEnabled,screwJammed=forceJam and processState==GeneratedControl.EXTRUSION);
  FilamentFormingSystem forming(material=material,fanPercent=100,gaugeValid=gaugeValid and not emergencyStop);
  DynamicSpoolSystem spool(gaugeValid=gaugeValid and not emergencyStop,spoolJammed=forceJam and processState==GeneratedControl.EXTRUSION,useExternalLineSpeed=true,externalLineSpeed=forming.pullerVelocity);
  Real busPower;
  Boolean feederEnable;
  Boolean pullerEnable;
  Boolean spoolerEnable;
  Boolean shredderDriveSafe;
  Boolean screwDriveSafe;
  Boolean heaterSafe;
  Boolean feederSafe;
  Boolean pullerSafe;
  Boolean spoolerSafe;
  Boolean powerBudgetSafe;
  Boolean mechanicalFuseStateSafe;
  Boolean restartInhibited;
  Boolean guardChainSafe;
  Boolean safeState;
equation
  shredderEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,1];
  screwEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,2];
  processHeaterEnabled=not emergencyStop and guardChainOK and GeneratedControl.permissions[processState,3];
  coolingEnabled=not emergencyStop and GeneratedControl.permissions[processState,7];
  feederEnable=GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and gaugeValid and not emergencyStop;
  pullerEnable=GeneratedControl.permissions[processState,5] and gaugeValid and not emergencyStop and not spool.safePause;
  spoolerEnable=GeneratedControl.permissions[processState,6] and gaugeValid and not emergencyStop and not spool.safePause;
  forming.massFlowGPH=extruder.netFlowGPH;
  forming.dieOutletTemperature=extruder.Tdie;
  forming.enabled=pullerEnable;
  busPower=24*abs(shredder.motor.current)+extruder.power1+extruder.power2+extruder.power3+extruder.powerDie+24*extruder.motorCurrent+24*spool.motorCurrent+(if coolingEnabled then 16 else 0)+29;
  shredderDriveSafe=(not shredder.motor.enable or shredderEnabled) and not (shredderEnabled and (screwEnabled or processHeaterEnabled));
  screwDriveSafe=not screwEnabled or (not shredderEnabled and not extruder.driveTripped);
  heaterSafe=(processHeaterEnabled or extruder.power1+extruder.power2+extruder.power3+extruder.powerDie<=1e-6) and not (extruder.thermalCut and extruder.power1+extruder.power2+extruder.power3+extruder.powerDie>1e-6);
  feederSafe=feederEnable== (GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and gaugeValid and not emergencyStop);
  pullerSafe=pullerEnable== (GeneratedControl.permissions[processState,5] and gaugeValid and not emergencyStop and not spool.safePause);
  spoolerSafe=spoolerEnable== (GeneratedControl.permissions[processState,6] and gaugeValid and not emergencyStop and not spool.safePause);
  powerBudgetSafe=busPower<=GeneratedControl.normalPhasePeakLimit;
  mechanicalFuseStateSafe=not shredder.inputFuse.broken or not shredder.motor.enable;
  restartInhibited=not (shredder.jamFault or extruder.driveTripped or spool.safePause) or (not shredder.motor.enable and not feederEnable);
  guardChainSafe=guardChainOK or (not shredder.motor.enable and not screwEnabled and not processHeaterEnabled and not feederEnable and not pullerEnable and not spoolerEnable);
  safeState=shredderDriveSafe and screwDriveSafe and heaterSafe and feederSafe and pullerSafe and spoolerSafe and powerBudgetSafe and mechanicalFuseStateSafe and restartInhibited and guardChainSafe;
end FullCoupledSystem;
