within PLA_PET_Recycler.Systems;
model FullCoupledSystem
  parameter Integer material=1;
  parameter Integer pendingMaterial=if material==1 then 2 else 1;
  parameter Integer processState=GeneratedControl.EXTRUSION;
  parameter Boolean gaugeValid=true;
  parameter Real gaugeU95=0.01;
  parameter Real gaugeFailureTime=1e9;
  parameter Real gaugeFailureDuration=1e9;
  parameter Real feederLossTime=1e9;
  parameter Real coolingLossTime=1e9;
  parameter Real coolingLossDuration=1e9;
  parameter Real explicitFaultClearTime=1e9;
  parameter Real pullerFailureTime=1e9;
  parameter Real pullerTachFirstPulseTime=0;
  parameter Real spoolerPermissionLossTime=1e9;
  parameter Real traversePermissionLossTime=1e9;
  parameter Real operatorRethreadConfirmationTime=1e9;
  parameter Real operatorRethreadSecondConfirmationTime=1e9;
  parameter Real operatorRethreadConfirmationDuration=0.5;
  parameter Integer formingInitialState=GeneratedControl.FORMING_NORMAL;
  parameter Boolean useQualificationFixture=false "Scenario fixture for independently qualified gauge/quality input";
  parameter Real purgeStartTime=0;
  parameter Boolean wastePathConfirmed=false;
  parameter Boolean purgeFeedApproved=true;
  parameter Boolean purgeVisualConfirmed=false;
  parameter Boolean screenCleanConfirmed=false;
  parameter Boolean hopperCleanConfirmed=false;
  parameter Boolean temperatureTransitionConfirmed=false;
  parameter Boolean finalMaterialConfirmed=false;
  parameter Boolean heaterSensorFault=false;
  parameter Boolean spoolJam=false;
  parameter Boolean forceJam=false;
  parameter Boolean emergencyStop=false;
  parameter Real emergencyStopTime=if emergencyStop then 0 else 1e9;
  parameter Boolean guardChainOK=true;
  Boolean emergencyStopActive;
  Boolean effectiveGaugeValid;
  Boolean coolingBaseDemand;
  Boolean coolingCommanded;
  Real coolingActuatorCommand(start=0,fixed=true);
  Real coolingFeedbackCurrent;
  Boolean coolingFeedbackValid;
  Boolean coolingMonitorArmed;
  discrete Boolean coolingHardFaultState(start=false,fixed=true);
  Boolean coolingHardFault;
  Boolean coolingFaultLatched;
  Integer detectedFaultReason;
  discrete Integer rawFaultReason(start=GeneratedControl.FAULT_NONE,fixed=true);
  Boolean formingFaultActive;
  Boolean pullerTachHealthy;
  Boolean pullerTachStartupGraceActive;
  Boolean pullerTachFailureActive;
  Boolean shredderEnabled;
  Boolean screwEnabled;
  Boolean processHeaterEnabled;
  Boolean coolingEnabled;
  Boolean feederEnable;
  Boolean pullerEnable;
  Boolean spoolerEnable;
  Boolean traverseEnable;
  Real screwScale;
  Real residualMeltState;
  Boolean spoolEligible;
  Boolean wasteMode;
  Boolean purgeStartPermitted;
  Boolean coolingStartupProven;
  Real coolingStartupHealthyDwell(start=0,fixed=true);
  Boolean purgeActive;
  Real purgeElapsed;
  Real purgeScrewRevolutions(start=0,fixed=true);
  Boolean purgeStableTemperature;
  Boolean purgeComplete;
  Boolean pendingMaterialActivated;
  discrete Real sampledDiameterError(start=0,fixed=true);
  discrete Real sampledOvality(start=0,fixed=true);
  discrete Boolean sampledPullerSaturated(start=false,fixed=true);
  discrete Boolean sampledQualityValid(start=false,fixed=true);
  discrete Boolean sampledStableFlow(start=false,fixed=true);
  discrete Boolean sampledDancerHardStop(start=false,fixed=true);
  discrete Boolean sampledDancerControlledStop(start=false,fixed=true);
  discrete Boolean sampledSpoolJam(start=false,fixed=true);
  discrete Boolean sampledCoolingCommanded(start=false,fixed=true);
  discrete Boolean sampledCoolingFailure(start=false,fixed=true);
  CoupledShredderSystem shredder(material=if forceJam then 4 else material,useExternalEnable=true,externalEnable=shredderEnabled);
  ThermalExtruderSystem extruder(material=material,useExternalCommands=true,externalHeaterCommand=processHeaterEnabled,externalHeaterPowerLimitW=GeneratedControl.heaterPowerLimitByState[processState],externalScrewCommand=screwEnabled,externalFeederCommand=feederEnable,externalScrewScale=screwScale,externalSafeHold=formingChain.state==GeneratedControl.FORMING_RUNDOWN or formingChain.state==GeneratedControl.FORMING_THERMAL_HOLD,screwJammed=forceJam and (processState==GeneratedControl.EXTRUSION or processState==GeneratedControl.MAINTENANCE_PURGE),sensorOpen=heaterSensorFault);
  FilamentFormingSystem forming(material=material,fanPercent=100,useExternalPermissions=true,externalCoolingEnabled=coolingEnabled,externalGaugeValid=effectiveGaugeValid and not emergencyStopActive);
  DynamicSpoolSystem spool(useExternalGaugeValid=true,externalGaugeValid=effectiveGaugeValid and not emergencyStopActive,spoolJammed=(forceJam or spoolJam) and processState==GeneratedControl.EXTRUSION,useExternalLineSpeed=true,externalLineSpeed=if spoolEligible then forming.pullerVelocity else 0,useExternalEnable=true,externalEnable=spoolerEnable,externalDemand=GeneratedControl.permissions[processState,6]);
  FormingChainSupervisor formingChain(material=material,initialState=formingInitialState,requestedFaultReason=detectedFaultReason,gaugeValid=effectiveGaugeValid,gaugeU95=gaugeU95,diameterError=sampledDiameterError,ovality=sampledOvality,pullerSaturated=sampledPullerSaturated,coolingFeedbackValid=coolingFeedbackValid,qualityValid=sampledQualityValid,stableFlow=sampledStableFlow,qualityInterlockArmed=processState==GeneratedControl.EXTRUSION and sampledStableFlow,emergencyStop=emergencyStopActive or coolingHardFault,operatorRethreadConfirmed=(time>=operatorRethreadConfirmationTime and time<operatorRethreadConfirmationTime+operatorRethreadConfirmationDuration) or (time>=operatorRethreadSecondConfirmationTime and time<operatorRethreadSecondConfirmationTime+operatorRethreadConfirmationDuration),explicitFaultClear=time>=explicitFaultClearTime);
  Real busPower;
  Boolean shredderDriveSafe;
  Boolean screwDriveSafe;
  Boolean heaterSafe;
  Boolean feederSafe;
  Boolean pullerSafe;
  Boolean spoolerSafe;
  Boolean powerBudgetSafe;
  Boolean mechanicalFuseStateSafe;
  Boolean restartInhibited;
  Boolean guardChainSafe;
  Boolean hardStopNominalSafe;
  Boolean safeState;
algorithm
  when initial() then
    sampledDiameterError := 0;
    sampledOvality := 0;
    sampledPullerSaturated := false;
    sampledQualityValid := false;
    sampledStableFlow := false;
    sampledDancerHardStop := false;
    sampledDancerControlledStop := false;
    sampledSpoolJam := false;
    sampledCoolingCommanded := false;
    sampledCoolingFailure := false;
    rawFaultReason := GeneratedControl.FAULT_NONE;
  elsewhen sample(0,GeneratedControl.gaugeSamplePeriod) then
    sampledDiameterError := if useQualificationFixture then 0 else forming.diameterError;
    sampledOvality := if useQualificationFixture then 0 else forming.measuredOvality;
    sampledPullerSaturated := if useQualificationFixture then false else forming.controlMargin<=1e-5;
    sampledQualityValid := if useQualificationFixture then effectiveGaugeValid else forming.qualitySampleValid;
    sampledStableFlow := extruder.ready and extruder.netFlowGPH>1;
    sampledDancerHardStop := spool.dancerHardStop;
    sampledDancerControlledStop := spool.dancerControlledStop;
    sampledSpoolJam := spool.jamDetected;
    sampledCoolingCommanded := coolingActuatorCommand>=GeneratedControl.coolingCommandThreshold/100;
    sampledCoolingFailure := sampledCoolingCommanded and coolingLossDuration>=GeneratedControl.coolingFeedbackDwell and time>=coolingLossTime+GeneratedControl.coolingFeedbackDwell and time<coolingLossTime+coolingLossDuration;
    rawFaultReason := if not effectiveGaugeValid then GeneratedControl.FAULT_GAUGE_INVALID else if sampledCoolingFailure then GeneratedControl.FAULT_COOLING_FAILURE else if pullerTachFailureActive then GeneratedControl.FAULT_PULLER_TACH_FAILURE else if sampledDancerHardStop then GeneratedControl.FAULT_DANCER_HARD_LIMIT else if sampledDancerControlledStop or sampledSpoolJam then GeneratedControl.FAULT_DANCER_CONTROLLED_STOP else if time>=spoolerPermissionLossTime then GeneratedControl.FAULT_SPOOLER_DRIVER_FAILURE else if time>=traversePermissionLossTime then GeneratedControl.FAULT_TRAVERSE_PERMISSION_LOSS else GeneratedControl.FAULT_NONE;
  end when;
algorithm
  when initial() then
    coolingHardFaultState := false;
  elsewhen sampledCoolingCommanded and processState<>GeneratedControl.EXTRUSION and processState<>GeneratedControl.REQUALIFYING and coolingLossDuration>=GeneratedControl.coolingFeedbackDwell and time>=coolingLossTime+GeneratedControl.coolingFeedbackDwell then
    coolingHardFaultState := true;
  elsewhen pre(coolingHardFaultState) and time>=explicitFaultClearTime and not (time>=coolingLossTime and time<coolingLossTime+coolingLossDuration) then
    coolingHardFaultState := false;
  end when;
equation
  emergencyStopActive=emergencyStop or time>=emergencyStopTime;
  effectiveGaugeValid=gaugeValid and not (time>=gaugeFailureTime and time<gaugeFailureTime+gaugeFailureDuration);
  coolingBaseDemand=GeneratedControl.permissions[processState,8] and not emergencyStopActive;
  der(coolingActuatorCommand)=((if coolingCommanded then 1 else 0)-coolingActuatorCommand)/0.02;
  coolingFeedbackCurrent=if coolingActuatorCommand>=0.5 and not (time>=coolingLossTime and time<coolingLossTime+coolingLossDuration) then 0.65 else 0.02;
  coolingFeedbackValid=coolingActuatorCommand>=0.5 and coolingFeedbackCurrent>=GeneratedControl.coolingCurrentMinimum and coolingFeedbackCurrent<=GeneratedControl.coolingCurrentMaximum;
  coolingMonitorArmed=coolingCommanded and coolingActuatorCommand>=GeneratedControl.coolingCommandThreshold/100;
  coolingFaultLatched=sampledCoolingFailure;
  coolingHardFault=coolingHardFaultState;
  detectedFaultReason=rawFaultReason;
  formingFaultActive=detectedFaultReason<>GeneratedControl.FAULT_NONE;
  pullerTachHealthy=time>=pullerTachFirstPulseTime and time<pullerFailureTime;
  pullerTachStartupGraceActive=GeneratedControl.permissions[processState,5] and time<GeneratedControl.pullerTachStartupGrace;
  pullerTachFailureActive=GeneratedControl.permissions[processState,5] and not pullerTachStartupGraceActive and not pullerTachHealthy;
  der(coolingStartupHealthyDwell)=if processState==GeneratedControl.MAINTENANCE_PURGE and coolingCommanded and coolingFeedbackValid then 1 else 0;
  when processState==GeneratedControl.MAINTENANCE_PURGE and not coolingFeedbackValid then
    reinit(coolingStartupHealthyDwell,0);
  end when;
  coolingStartupProven=processState<>GeneratedControl.MAINTENANCE_PURGE or coolingStartupHealthyDwell>=GeneratedControl.coolingStartupProbeDwell;
  purgeStartPermitted=processState==GeneratedControl.MAINTENANCE_PURGE and wastePathConfirmed and purgeFeedApproved and coolingStartupProven and guardChainOK and not emergencyStopActive and not coolingHardFault and not heaterSensorFault and not extruder.driveTripped;
  purgeActive=purgeStartPermitted and time>=purgeStartTime and not purgeComplete;
  purgeElapsed=max(0,time-purgeStartTime);
  der(purgeScrewRevolutions)=if purgeActive and screwEnabled then max(0,extruder.screwRPM)/60 else 0;
  purgeStableTemperature=extruder.ready;
  purgeComplete=purgeStartPermitted and time>=purgeStartTime and purgeElapsed>=GeneratedControl.purgeMinTime and purgeScrewRevolutions>=GeneratedControl.purgeMinScrewRevolutions and purgeStableTemperature and not extruder.driveTripped and not heaterSensorFault and not sampledCoolingFailure and purgeVisualConfirmed;
  pendingMaterialActivated=purgeComplete and screenCleanConfirmed and hopperCleanConfirmed and temperatureTransitionConfirmed and finalMaterialConfirmed;
  shredderEnabled=not emergencyStopActive and not coolingHardFault and guardChainOK and GeneratedControl.permissions[processState,1];
  screwScale=if processState==GeneratedControl.MAINTENANCE_PURGE then GeneratedControl.purgeScrewScale else formingChain.screwRundownScale;
  screwEnabled=not emergencyStopActive and not coolingHardFault and guardChainOK and GeneratedControl.permissions[processState,2] and (if processState==GeneratedControl.MAINTENANCE_PURGE then purgeActive else formingChain.screwPermitted);
  processHeaterEnabled=not emergencyStopActive and not coolingHardFault and guardChainOK and GeneratedControl.permissions[processState,3] and (if processState==GeneratedControl.MAINTENANCE_PURGE then coolingStartupProven else formingChain.heaterPermitted);
  coolingCommanded=coolingBaseDemand and guardChainOK and not emergencyStopActive and not pre(coolingHardFaultState) and (if processState==GeneratedControl.MAINTENANCE_PURGE then true else formingChain.coolingPermitted);
  coolingEnabled=coolingCommanded;
  feederEnable=GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and not emergencyStopActive and not coolingHardFault and time<feederLossTime and (if processState==GeneratedControl.MAINTENANCE_PURGE then purgeActive else formingChain.feederPermitted);
  pullerEnable=GeneratedControl.permissions[processState,5] and not emergencyStopActive and not coolingHardFault and (if processState==GeneratedControl.MAINTENANCE_PURGE then purgeActive else formingChain.pullerPermitted);
  spoolEligible=processState==GeneratedControl.EXTRUSION and formingChain.spoolEligible and (if useQualificationFixture then sampledQualityValid and not sampledPullerSaturated else forming.spoolEligible) and effectiveGaugeValid and coolingFeedbackValid;
  wasteMode=processState==GeneratedControl.MAINTENANCE_PURGE or formingChain.wasteMode or not spoolEligible;
  spoolerEnable=GeneratedControl.permissions[processState,6] and spoolEligible and not emergencyStopActive and not coolingHardFault and time<spoolerPermissionLossTime;
  traverseEnable=GeneratedControl.permissions[processState,7] and spoolEligible and not emergencyStopActive and not coolingHardFault and time<traversePermissionLossTime;
  forming.massFlowGPH=extruder.netFlowGPH;
  forming.dieOutletTemperature=extruder.Tdie;
  forming.enabled=pullerEnable;
  residualMeltState=extruder.feedInventoryG+0.02*max(0,extruder.Tdie-100);
  busPower=24*abs(shredder.motor.current)+0.08*24*abs(shredder.motor.current)+extruder.power1+extruder.power2+extruder.power3+extruder.powerDie+24*extruder.motorCurrent+(if feederEnable then 8 else 0)+(if pullerEnable then 12 else 0)+(if spoolerEnable then 24*spool.motorCurrent else 0)+(if traverseEnable then 4 else 0)+(if coolingEnabled then 16 else 0)+29;
  shredderDriveSafe=(not shredder.motor.enable or shredderEnabled) and not (shredderEnabled and (screwEnabled or processHeaterEnabled));
  screwDriveSafe=not screwEnabled or (not shredderEnabled and not extruder.driveTripped and screwScale>=0 and screwScale<=1);
  heaterSafe=(processHeaterEnabled or extruder.power1+extruder.power2+extruder.power3+extruder.powerDie<=1e-6) and not (extruder.thermalCut and extruder.power1+extruder.power2+extruder.power3+extruder.powerDie>1e-6);
  feederSafe=not feederEnable or (GeneratedControl.permissions[processState,4] and extruder.ready and not extruder.driveTripped and not emergencyStopActive and (not spoolerEnable or spoolEligible));
  pullerSafe=not pullerEnable or (GeneratedControl.permissions[processState,5] and not emergencyStopActive);
  spoolerSafe=not spoolerEnable or (GeneratedControl.permissions[processState,6] and spoolEligible and not emergencyStopActive);
  powerBudgetSafe=busPower<=GeneratedControl.normalPhasePeakLimit and GeneratedControl.psuRating-busPower>=GeneratedControl.minimumReserve;
  mechanicalFuseStateSafe=not shredder.inputFuse.broken or not shredder.motor.enable;
  restartInhibited=not (shredder.jamFault or extruder.driveTripped or formingFaultActive) or (not spoolerEnable and not traverseEnable and not feederEnable);
  guardChainSafe=guardChainOK or (not shredder.motor.enable and not screwEnabled and not processHeaterEnabled and not feederEnable and not pullerEnable and not spoolerEnable);
  hardStopNominalSafe=not spool.dancerHardStop;
  safeState=shredderDriveSafe and screwDriveSafe and heaterSafe and feederSafe and pullerSafe and spoolerSafe and powerBudgetSafe and mechanicalFuseStateSafe and restartInhibited and guardChainSafe and hardStopNominalSafe;
end FullCoupledSystem;
