within PLA_PET_Recycler.Systems;
model ProcessArbitrationSystem
  parameter Integer initialState=GeneratedControl.IDLE;
  parameter Integer nextState=initialState;
  parameter Real transitionTime=1e9;
  parameter Boolean illegalOverlapRequest=false;
  discrete Integer processState(start=initialState,fixed=true);
  Boolean requestedShredder;
  Boolean requestedHeater;
  Boolean shredderEnabled;
  Boolean screwEnabled;
  Boolean processHeaterEnabled;
  Boolean feederEnabled;
  Boolean pullerEnabled;
  Boolean spoolerEnabled;
  Boolean traverseEnabled;
  Boolean coolingEnabled;
  Boolean overlapBlocked;
  Real shredderCurrent(start=0,fixed=true);
  Real shredderMotorPower;
  Real driverLossPower;
  Real heaterDuty;
  Real heaterPower;
  Real screwDrivePower;
  Real feederPower;
  Real pullerPower;
  Real spoolerPower;
  Real traversePower;
  Real coolingPower;
  Real electronicsPower;
  Real phaseAveragePower;
  Real phasePeakPower;
  Real psuCurrent;
  Real remainingWattMargin;
  Real remainingAmpereMargin;
  Boolean powerBudgetSafe;
equation
  when time>=transitionTime then
    processState=nextState;
  end when;
  requestedShredder=GeneratedControl.permissions[processState,1] or illegalOverlapRequest;
  requestedHeater=GeneratedControl.permissions[processState,3] or illegalOverlapRequest;
  shredderEnabled=requestedShredder and processState==GeneratedControl.SHREDDING;
  processHeaterEnabled=requestedHeater and not shredderEnabled and abs(shredderCurrent)<0.5;
  screwEnabled=GeneratedControl.permissions[processState,2] and not shredderEnabled;
  feederEnabled=GeneratedControl.permissions[processState,4] and screwEnabled;
  pullerEnabled=GeneratedControl.permissions[processState,5];
  spoolerEnabled=GeneratedControl.permissions[processState,6];
  traverseEnabled=spoolerEnabled;
  coolingEnabled=GeneratedControl.permissions[processState,7];
  overlapBlocked=not (shredderEnabled and (screwEnabled or processHeaterEnabled));

  der(shredderCurrent)=((if shredderEnabled then 17.2 else 0)-shredderCurrent)/0.35;
  shredderMotorPower=24*max(0,shredderCurrent);
  driverLossPower=if shredderEnabled then 0.08*shredderMotorPower else 0;
  heaterDuty=if not processHeaterEnabled then 0 else if processState==GeneratedControl.PREHEATING then 1 else max(0.70,min(0.84,0.77+0.07*sin(0.7*time)));
  heaterPower=360*heaterDuty;
  screwDrivePower=if screwEnabled then 74+8*sin(1.3*time)^2 else 0;
  feederPower=if feederEnabled then 8 else 0;
  pullerPower=if pullerEnabled then 12 else 0;
  spoolerPower=if spoolerEnabled then 10 else 0;
  traversePower=if traverseEnabled then 4 else 0;
  coolingPower=if coolingEnabled then 16 else 0;
  electronicsPower=29;
  phasePeakPower=shredderMotorPower+driverLossPower+heaterPower+screwDrivePower+feederPower+pullerPower+spoolerPower+traversePower+coolingPower+electronicsPower;
  phaseAveragePower=phasePeakPower;
  psuCurrent=phasePeakPower/24;
  remainingWattMargin=GeneratedControl.psuRating-phasePeakPower;
  remainingAmpereMargin=remainingWattMargin/24;
  powerBudgetSafe=phasePeakPower<=GeneratedControl.normalPhasePeakLimit and remainingWattMargin>=100;
end ProcessArbitrationSystem;
