within PLA_PET_Recycler.Systems;
model ShredderSystem
  parameter Integer loadMode=1;
  parameter Real jamStart=1e9;
  parameter Real stopTime=1e9;
  parameter Real forcedLoad=0;
  parameter Real forcedRequest=0;
  parameter Boolean retryLogic=false;
  parameter Real phaseComplianceRadPerNm=0.00035;
  parameter Real phaseBacklashRad=0.006;
  Components.CalibratedDCDrive drive;
  Components.InputTorqueFuse inputFuse;
  Components.CutterLoadSurrogate load(mode=loadMode,jamStart=jamStart,forcedLoad=forcedLoad);
  Components.CutterRotor rightRotor;
  Components.CutterRotor leftRotor;
  Components.ChainReduction chain(ratio=2.0,efficiency=0.90);
  Components.PhaseGearPair phase(stiffness=2200,damping=1.5,backlash=phaseBacklashRad);
  Components.SafetyController controller(jamStart=if retryLogic then jamStart else 1e9);
  Real speedCommand;
  Real requestedTorque;
  Real transmittedTorque;
  Real cutterTorque;
  Real phaseError;
  Real phaseTorque;
  Real phaseSeparatingForce;
  Real chainForce;
  Real bearingLoad;
  Real frameReaction;
  Real rightToothAngle;
  Real leftToothAngle;
  Boolean electricalTrip;
  Boolean fuseOperating;
  Boolean faultLatched;
  Integer retryCount;
equation
  controller.permission=time<stopTime;
  retryCount=controller.retryCount;
  faultLatched=controller.latchedFault;
  speedCommand=32*2*Modelica.Constants.pi/60;
  requestedTorque=if time>=stopTime or faultLatched then 0 else
    (if retryLogic then controller.commandSign else 1)*(forcedRequest+min(Parameters.normalTorque,load.torque)+0.8*(speedCommand-abs(rightRotor.speed)));
  inputFuse.requestedTorque=requestedTorque;
  transmittedTorque=inputFuse.transmittedTorque;
  fuseOperating=inputFuse.operating;
  drive.torqueRequest=transmittedTorque;
  drive.enable=time<stopTime and not faultLatched;
  cutterTorque=drive.torque;
  chain.motorTorque=cutterTorque/(chain.ratio*chain.efficiency);
  chain.motorAngle=rightRotor.angle*chain.ratio;
  chain.cutterAngle=rightRotor.angle;
  rightRotor.driveTorque=cutterTorque-phaseTorque;
  rightRotor.loadTorque=load.torque/2*tanh(20*rightRotor.speed);
  leftRotor.driveTorque=-phaseTorque;
  leftRotor.loadTorque=load.torque/2*tanh(20*leftRotor.speed);
  phase.rightAngle=rightRotor.angle;
  phase.leftAngle=leftRotor.angle;
  phaseError=phase.phaseError;
  phaseTorque=phase.meshTorque;
  phaseSeparatingForce=phase.separatingForce;
  chainForce=chain.tightSideForce;
  bearingLoad=load.torque/(2*0.029)+chainForce+phaseSeparatingForce;
  frameReaction=bearingLoad+abs(cutterTorque)/0.12;
  rightToothAngle=mod(rightRotor.angle,2*Modelica.Constants.pi/7);
  leftToothAngle=mod(-leftRotor.angle,2*Modelica.Constants.pi/7);
  electricalTrip=abs(load.torque)>=Parameters.electricalTripTorque;
end ShredderSystem;
