within PLA_PET_Recycler.Systems;
model ThermalExtruderSystem
  parameter Integer material=1 "1 PLA, 2 PET";
  parameter Real targetRPM=if material==1 then 16 else 18;
  parameter Real ambient=25 "degC";
  parameter Integer heaterOpenZone=0 "0 none, 1..4 failed open";
  parameter Integer stuckOnZone=0 "0 none, 1..4 MOSFET stuck on";
  parameter Boolean sensorOpen=false;
  parameter Boolean screwJammed=false;
  parameter Boolean enabled=true;
  parameter Boolean heaterEnabled=enabled;
  parameter Boolean screwEnabled=enabled;
  parameter Boolean useExternalCommands=false;
  input Boolean externalHeaterCommand=false;
  input Boolean externalScrewCommand=false;
  Boolean heaterCommand;
  Boolean screwCommand;
  parameter Real blockageStart=1e9;
  parameter Real blockageRamp=120;
  parameter Real maximumBlockage=0.92;
  parameter Real bulkDensity=330 "kg/m3 PLA nominal; scenario override for PET";
  parameter Real fillFactor=0.22;
  Real T1(start=25,fixed=true);
  Real T2(start=25,fixed=true);
  Real T3(start=25,fixed=true);
  Real Tdie(start=25,fixed=true);
  Real sensorT1;
  Real sensorT2;
  Real sensorT3;
  Real sensorTdie;
  Real targetT1;
  Real targetT2;
  Real targetT3;
  Real targetTdie;
  Real duty1;
  Real duty2;
  Real duty3;
  Real dutyDie;
  Real power1;
  Real power2;
  Real power3;
  Real powerDie;
  Real screwRPM;
  Real screwOmega(start=0,fixed=true);
  Real commandedScrewRPM;
  Real motorTorque;
  Real motorCurrent;
  Real polymerTorque;
  Real meltPressureMPa;
  Real blockageFraction;
  Real solidConveyingGPH;
  Real meltEfficiency;
  Real viscosityFactor;
  Real backflowGPH;
  Real leakageGPH;
  Real netFlowGPH;
  Real potentialFlowGPH;
  Real polymerLoad1;
  Real polymerLoad2;
  Real polymerLoad3;
  Real polymerLoadDie;
  discrete Boolean fuseBlown(start=false,fixed=true);
  discrete Boolean driveTripped(start=false,fixed=true);
  Boolean thermalCut;
  Boolean ready;
  Boolean torqueTrip;
equation
  heaterCommand=if useExternalCommands then externalHeaterCommand else heaterEnabled;
  screwCommand=if useExternalCommands then externalScrewCommand else screwEnabled;
  targetT1=(if material==1 then 180 else 245)-(if driveTripped then 20 else 0);
  targetT2=(if material==1 then 195 else 260)-(if driveTripped then 20 else 0);
  targetT3=(if material==1 then 205 else 270)-(if driveTripped then 20 else 0);
  targetTdie=(if material==1 then 200 else 265)-(if driveTripped then 20 else 0);
  sensorT1=if sensorOpen then -273 else T1;
  sensorT2=if sensorOpen then -273 else T2;
  sensorT3=if sensorOpen then -273 else T3;
  sensorTdie=if sensorOpen then -273 else Tdie;
  when max(max(T1,T2),max(T3,Tdie))>=300 then
    fuseBlown=true;
  end when;
  thermalCut=fuseBlown;
  duty1=if stuckOnZone==1 then 1 else if sensorOpen or thermalCut or not heaterCommand then 0 else max(0,min(1,0.20*(targetT1-sensorT1)));
  duty2=if stuckOnZone==2 then 1 else if sensorOpen or thermalCut or not heaterCommand then 0 else max(0,min(1,0.20*(targetT2-sensorT2)));
  duty3=if stuckOnZone==3 then 1 else if sensorOpen or thermalCut or not heaterCommand then 0 else max(0,min(1,0.20*(targetT3-sensorT3)));
  dutyDie=if stuckOnZone==4 then 1 else if sensorOpen or thermalCut or not heaterCommand then 0 else max(0,min(1,0.20*(targetTdie-sensorTdie)));
  power1=if fuseBlown or heaterOpenZone==1 then 0 else 100*duty1;
  power2=if fuseBlown or heaterOpenZone==2 then 0 else 100*duty2;
  power3=if fuseBlown or heaterOpenZone==3 then 0 else 100*duty3;
  powerDie=if fuseBlown or heaterOpenZone==4 then 0 else 60*dutyDie;
  blockageFraction=if screwJammed then 0.99 else if time<blockageStart then 0 else min(maximumBlockage,(time-blockageStart)/blockageRamp*maximumBlockage);
  commandedScrewRPM=if screwCommand and not thermalCut and ready and not driveTripped then targetRPM else 0;
  screwRPM=screwOmega*60/(2*Modelica.Constants.pi);
  solidConveyingGPH=(if material==1 then 8.18 else 7.21)*screwRPM*(bulkDensity/330)*fillFactor/0.22;
  meltEfficiency=max(0,min(0.98,0.72+0.0012*(T2-ambient)+0.0008*(T3-ambient)));
  viscosityFactor=exp((if material==1 then 1750 else 2300)*(1/(Tdie+273.15)-1/(targetTdie+273.15)));
  potentialFlowGPH=max(0,solidConveyingGPH*meltEfficiency);
  meltPressureMPa=min(8,3.0*potentialFlowGPH/100*(1+5*blockageFraction/max(0.08,1-blockageFraction)));
  backflowGPH=max(0,0.08*potentialFlowGPH*viscosityFactor*(1+meltPressureMPa/6));
  leakageGPH=max(0,0.035*potentialFlowGPH*viscosityFactor*(1+meltPressureMPa/6));
  netFlowGPH=max(0,potentialFlowGPH*(1-blockageFraction)-backflowGPH-leakageGPH);
  polymerTorque=1.5+2.5*meltPressureMPa;
  motorTorque=max(-22,min(22,0.8*(commandedScrewRPM*2*Modelica.Constants.pi/60-screwOmega)+polymerTorque));
  motorCurrent=abs(motorTorque)/1.50;
  0.08*der(screwOmega)=motorTorque-polymerTorque-0.05*screwOmega;
  when meltPressureMPa>=6 or abs(motorTorque)>=21.9 or motorCurrent>=14.6 then
    driveTripped=true;
  end when;
  polymerLoad1=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T1-ambient)*0.28;
  polymerLoad2=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T2-T1)*0.32;
  polymerLoad3=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T3-T2)*0.25;
  polymerLoadDie=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,Tdie-T3)*0.15;
  170*der(T1)=power1-0.25*(T1-ambient)-1.0*(T1-T2)-polymerLoad1;
  165*der(T2)=power2-0.25*(T2-ambient)+1.0*(T1-T2)-1.0*(T2-T3)-polymerLoad2;
  160*der(T3)=power3-0.25*(T3-ambient)+1.0*(T2-T3)-0.8*(T3-Tdie)-polymerLoad3;
  95*der(Tdie)=powerDie-0.22*(Tdie-ambient)+0.8*(T3-Tdie)-polymerLoadDie;
  ready=abs(T1-targetT1)<5 and abs(T2-targetT2)<5 and abs(T3-targetT3)<5 and abs(Tdie-targetTdie)<5 and not sensorOpen;
  torqueTrip=driveTripped;
end ThermalExtruderSystem;
