within PLA_PET_Recycler.Systems;
model ThermalExtruderSystem
  parameter Integer material=1 "1 PLA, 2 PET";
  parameter Real targetRPM=18;
  parameter Real ambient=25 "degC";
  parameter Integer heaterOpenZone=0 "0 none, 1..4 failed open";
  parameter Integer stuckOnZone=0 "0 none, 1..4 MOSFET stuck on";
  parameter Boolean sensorOpen=false;
  parameter Boolean screwJammed=false;
  parameter Boolean enabled=true;
  parameter Real bulkDensity=330 "kg/m3 PLA nominal; scenario override for PET";
  parameter Real fillFactor=0.22;
  Real T1(start=25,fixed=true);
  Real T2(start=25,fixed=true);
  Real T3(start=25,fixed=true);
  Real Tdie(start=25,fixed=true);
  Real sensorT1;
  Real sensorT2;
  Real sensorT3;
  Real sensorTdie;
  Real targetT1;
  Real targetT2;
  Real targetT3;
  Real targetTdie;
  Real duty1;
  Real duty2;
  Real duty3;
  Real dutyDie;
  Real power1;
  Real power2;
  Real power3;
  Real powerDie;
  Real screwRPM;
  Real solidConveyingGPH;
  Real meltEfficiency;
  Real viscosityFactor;
  Real backflowGPH;
  Real leakageGPH;
  Real netFlowGPH;
  Real polymerLoad1;
  Real polymerLoad2;
  Real polymerLoad3;
  Real polymerLoadDie;
  discrete Boolean fuseBlown(start=false,fixed=true);
  Boolean thermalCut;
  Boolean ready;
  Boolean torqueTrip;
equation
  targetT1=if material==1 then 180 else 245;
  targetT2=if material==1 then 195 else 260;
  targetT3=if material==1 then 205 else 270;
  targetTdie=if material==1 then 200 else 265;
  sensorT1=if sensorOpen then -273 else T1;
  sensorT2=if sensorOpen then -273 else T2;
  sensorT3=if sensorOpen then -273 else T3;
  sensorTdie=if sensorOpen then -273 else Tdie;
  when max(max(T1,T2),max(T3,Tdie))>=300 then
    fuseBlown=true;
  end when;
  thermalCut=fuseBlown;
  duty1=if stuckOnZone==1 then 1 else if sensorOpen or thermalCut or not enabled then 0 else max(0,min(1,0.20*(targetT1-sensorT1)));
  duty2=if stuckOnZone==2 then 1 else if sensorOpen or thermalCut or not enabled then 0 else max(0,min(1,0.20*(targetT2-sensorT2)));
  duty3=if stuckOnZone==3 then 1 else if sensorOpen or thermalCut or not enabled then 0 else max(0,min(1,0.20*(targetT3-sensorT3)));
  dutyDie=if stuckOnZone==4 then 1 else if sensorOpen or thermalCut or not enabled then 0 else max(0,min(1,0.20*(targetTdie-sensorTdie)));
  power1=if fuseBlown or heaterOpenZone==1 then 0 else 100*duty1;
  power2=if fuseBlown or heaterOpenZone==2 then 0 else 100*duty2;
  power3=if fuseBlown or heaterOpenZone==3 then 0 else 100*duty3;
  powerDie=if fuseBlown or heaterOpenZone==4 then 0 else 60*dutyDie;
  screwRPM=if enabled and not screwJammed and not thermalCut and ready then targetRPM else 0;
  solidConveyingGPH=6.8*screwRPM*(bulkDensity/330)*fillFactor/0.22;
  meltEfficiency=max(0,min(0.98,0.72+0.0012*(T2-ambient)+0.0008*(T3-ambient)));
  viscosityFactor=exp((if material==1 then 1750 else 2300)*(1/(Tdie+273.15)-1/(targetTdie+273.15)));
  backflowGPH=max(0,0.08*solidConveyingGPH*viscosityFactor);
  leakageGPH=max(0,0.035*solidConveyingGPH*(0.30/0.30)^3*viscosityFactor);
  netFlowGPH=max(0,solidConveyingGPH*meltEfficiency-backflowGPH-leakageGPH);
  polymerLoad1=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T1-ambient)*0.28;
  polymerLoad2=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T2-T1)*0.32;
  polymerLoad3=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,T3-T2)*0.25;
  polymerLoadDie=netFlowGPH/3.6e6*(if material==1 then 1800 else 1200)*max(0,Tdie-T3)*0.15;
  170*der(T1)=power1-0.25*(T1-ambient)-1.0*(T1-T2)-polymerLoad1;
  165*der(T2)=power2-0.25*(T2-ambient)+1.0*(T1-T2)-1.0*(T2-T3)-polymerLoad2;
  160*der(T3)=power3-0.25*(T3-ambient)+1.0*(T2-T3)-0.8*(T3-Tdie)-polymerLoad3;
  95*der(Tdie)=powerDie-0.22*(Tdie-ambient)+0.8*(T3-Tdie)-polymerLoadDie;
  ready=abs(T1-targetT1)<5 and abs(T2-targetT2)<5 and abs(T3-targetT3)<5 and abs(Tdie-targetTdie)<5 and not sensorOpen;
  torqueTrip=screwJammed;
end ThermalExtruderSystem;
