#!/usr/bin/env python3
"""단일 JSON 계약에서 OpenModelica 제어 상수를 생성한다."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROCESS_PATH = ROOT / "control/process_contract.json"
FAULT_PATH = ROOT / "control/fault_response_contract.json"
MODELICA_PATH = ROOT / "simulation/openmodelica/PLA_PET_Recycler/GeneratedControl.mo"
SCENARIO_CONTRACT_PATH = ROOT / "control/orchestration_scenario_contract.json"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def real(value: float | int) -> str:
    return f"{float(value):.12g}"


def main() -> None:
    process = json.loads(PROCESS_PATH.read_text())
    fault = json.loads(FAULT_PATH.read_text())
    scenario_contract = json.loads(SCENARIO_CONTRACT_PATH.read_text())
    if process["revision"] != fault["revision"]:
        raise SystemExit("process/fault revision mismatch")
    if scenario_contract["revision"] != process["revision"]:
        raise SystemExit("scenario/process revision mismatch")
    required_scenario_fields = set(scenario_contract["required_fields"])
    for scenario, record in scenario_contract["scenarios"].items():
        if set(record) != required_scenario_fields:
            raise SystemExit(f"scenario evidence field mismatch: {scenario}")
        model_path = ROOT / "simulation/openmodelica/PLA_PET_Recycler/Scenarios" / f"{scenario}.mo"
        if not model_path.exists():
            raise SystemExit(f"scenario evidence has no Modelica model: {scenario}")

    states = list(process["states"])
    actuators = process["actuator_order"]
    material_states = process["material_session"]["states"]
    forming_states = process["forming_chain"]["states"]
    fault_reasons = process["forming_chain"]["fault_reasons"]
    phase_names = list(process["power"]["phases"])
    calibration_domains = ["drive", "gauge", "current_sensor", "temperature_channels", "cooling_feedback"]
    permissions = [
        ",".join(str(bool(process["states"][state][a])).lower() for a in actuators)
        for state in states
    ]
    transitions = [
        ",".join(str(target in process["transitions"][source]).lower() for target in states)
        for source in states
    ]
    readiness = [
        ",".join(str(domain in process["calibration_readiness"]["state_requirements"].get(state, [])).lower() for domain in calibration_domains)
        for state in states
    ]

    if set(process["transitions"]) != set(states):
        raise SystemExit("transition source set does not match process states")
    if any(target not in states for targets in process["transitions"].values() for target in targets):
        raise SystemExit("transition target is not a process state")

    readiness_contract = process["calibration_readiness"]
    for domain in calibration_domains:
        declared = set(readiness_contract[domain]["required_for"])
        matrix = {
            state
            for state, required in readiness_contract["state_requirements"].items()
            if domain in required
        }
        if declared != matrix:
            raise SystemExit(
                f"calibration required_for/state_requirements mismatch: {domain} "
                f"declared={sorted(declared)} matrix={sorted(matrix)}"
            )

    startup_probe = process["cooling_feedback"]["startup_probe"]
    if startup_probe["healthy_feedback_dwell_s"] != fault["timing"]["cooling_feedback_dwell_s"]:
        raise SystemExit("cooling startup probe/fault feedback dwell mismatch")

    for name, values in process["power"]["phases"].items():
        average_sum = sum(values["components_average_w"])
        peak_sum = sum(values["components_peak_w"])
        if abs(average_sum - values["average_w"]) > 1e-9 or abs(peak_sum - values["peak_w"]) > 1e-9:
            raise SystemExit(f"power component sum mismatch: {name}")

    lines = [
        "within PLA_PET_Recycler;",
        "package GeneratedControl",
        "  // AUTO-GENERATED by control/generate_contract_artifacts.py; do not edit.",
        f'  constant String revision="{process["revision"]}";',
        f'  constant String processContractSha256="{digest(PROCESS_PATH)}";',
        f'  constant String faultResponseContractSha256="{digest(FAULT_PATH)}";',
    ]
    lines += [f"  constant Integer {name}={i};" for i, name in enumerate(states, 1)]
    lines += [f"  constant Integer MATERIAL_{name}={i};" for i, name in enumerate(material_states, 1)]
    lines += [f"  constant Integer FORMING_{name}={i};" for i, name in enumerate(forming_states, 1)]
    lines += [f"  constant Integer FAULT_{name}={i - 1};" for i, name in enumerate(fault_reasons, 1)]
    lines += [
        f"  constant Boolean permissions[{len(states)},{len(actuators)}]=[" + ";".join(permissions) + "];",
        f"  constant Boolean transitionAllowed[{len(states)},{len(states)}]=[" + ";".join(transitions) + "];",
        f"  constant Boolean calibrationRequired[{len(states)},{len(calibration_domains)}]=[" + ";".join(readiness) + "];",
        f"  constant Real purgeMinTime={real(process['purge']['minimum_elapsed_s'])};",
        f"  constant Real purgeMinScrewRevolutions={real(process['purge']['minimum_screw_revolutions'])};",
        f"  constant Real purgeScrewScale={real(process['purge']['screw_scale'])};",
        f"  constant Boolean purgeFeedApprovalSingleUse={str(process['purge']['feed_approval_single_use']).lower()};",
        f"  constant Real purgeTemperatureBand={real(process['purge']['stable_temperature_band_c'])};",
        f"  constant Real rundownDuration={real(fault['timing']['screw_rundown_s'])};",
        f"  constant Real pullerWasteDuration={real(fault['timing']['puller_waste_s'])};",
        f"  constant Real pullerTachStartupGrace={real(fault['timing']['puller_tach_startup_grace_s'])};",
        f"  constant Real thermalHoldDuration={real(fault['timing']['thermal_hold_s'])};",
        f"  constant Real faultResponseLatency={real(fault['timing']['maximum_response_latency_s'])};",
        f"  constant Real coolingFeedbackDwell={real(fault['timing']['cooling_feedback_dwell_s'])};",
        f"  constant Integer requalGaugeSamples={process['requalification']['minimum_consecutive_valid_samples']};",
        f"  constant Real gaugeSamplePeriod={real(process['requalification']['gauge_sample_period_s'])};",
        f"  constant Real requalU95Max={real(process['requalification']['u95_max_mm'])};",
        f"  constant Real diameterTarget={real(process['requalification']['diameter_target_mm'])};",
        f"  constant Real requalDiameterTolerance={real(process['requalification']['diameter_tolerance_mm'])};",
        f"  constant Real requalStableDuration={real(process['requalification']['diameter_stable_duration_s'])};",
        f"  constant Real requalOvalityMax={real(process['requalification']['ovality_max_mm'])};",
        f"  constant Real transportDelayByMaterial[2]={{{real(process['requalification']['transport_delay_s']['PLA'])},{real(process['requalification']['transport_delay_s']['PET'])}}};",
        f"  constant Real dancerWarning={real(process['dancer']['warning_rad'])};",
        f"  constant Real dancerControlledStop={real(process['dancer']['controlled_stop_rad'])};",
        f"  constant Real dancerHardStop={real(process['dancer']['mechanical_hard_stop_rad'])};",
        f"  constant Real dancerHardStopStiffness={real(process['dancer']['hard_stop_stiffness_nm_per_rad'])};",
        f"  constant Real dancerHardStopDamping={real(process['dancer']['hard_stop_damping_nms_per_rad'])};",
        f"  constant Real coolingCommandThreshold={real(process['cooling_feedback']['command_threshold_percent'])};",
        f"  constant Real coolingCurrentMinimum={real(process['cooling_feedback']['healthy_current_window_a'][0])};",
        f"  constant Real coolingCurrentMaximum={real(process['cooling_feedback']['healthy_current_window_a'][1])};",
        f"  constant Real coolingStartupProbeDwell={real(startup_probe['healthy_feedback_dwell_s'])};",
        f"  constant Real coolingStartupProbeTimeout={real(startup_probe['timeout_s'])};",
        f"  constant Real coolingStartupProbeCommandByMaterial[2]={{{real(startup_probe['command_percent_by_material']['PLA'])},{real(startup_probe['command_percent_by_material']['PET'])}}};",
        "  constant Boolean coolingStartupProbeFanOnly=true;",
        f"  constant Boolean coolingStartupProbeRequiredByState[{len(states)}]={{{','.join(str(state in startup_probe['required_for_requested_phases']).lower() for state in states)}}};",
        f"  constant Real cooldownMaximumProcessTemperature={real(process['cooldown_completion']['max_process_temperature_c'])};",
        f"  constant Real jamStartupGrace={real(process['jam']['startup_grace_ms']/1000)};",
        f"  constant Real jamRPMDeficitRatio={real(process['jam']['rpm_deficit_ratio'])};",
        f"  constant Real jamCurrentSensorSaturation={real(process['jam']['current_sensor_saturation_a'])};",
        f"  constant Real jamTripTorque={real(process['jam']['jam_trip_torque_nm'])};",
        f"  constant Real driveNoLoadCurrent={real(process['drive_reference_calibration']['no_load_current_a'])};",
        f"  constant Real driveTorquePerAmp={real(process['drive_reference_calibration']['torque_per_amp_nm'])};",
        f"  constant Real driveMotorToCutterRatio={real(process['drive_reference_calibration']['motor_to_cutter_ratio'])};",
        f"  constant Real driveEfficiency={real(process['drive_reference_calibration']['drivetrain_efficiency'])};",
        f"  constant Integer maximumRetries={process['jam']['maximum_retries']};",
        f"  constant Real shredderDutyLimit={real(process['shredder_speed_control']['duty_limit'])};",
        f"  constant Real shredderCommandFilter={real(process['shredder_speed_control']['command_filter_s'])};",
        f"  constant Real shredderMeasurementFilter={real(process['shredder_speed_control']['measurement_filter_s'])};",
        f"  constant Real shredderDutyBiasByMaterial[2]={{{real(process['materials']['PLA']['shredder_duty_bias'])},{real(process['materials']['PET']['shredder_duty_bias'])}}};",
        f"  constant Real shredderSpeedKpByMaterial[2]={{{real(process['materials']['PLA']['shredder_speed_kp'])},{real(process['materials']['PET']['shredder_speed_kp'])}}};",
        f"  constant Real normalPhasePeakLimit={real(process['power']['normal_phase_peak_limit_w'])};",
        f"  constant Real psuRating={real(process['power']['psu_rating_w'])};",
        f"  constant Real minimumReserve={real(process['power']['minimum_reserve_w'])};",
        f"  constant Real estopMaximumZeroLatency={real(process['safety_invariant_evidence']['estop_zeros_hazardous_outputs_within_one_supervisor_cycle']['maximum_cycle_s'])};",
        "  constant Boolean atomicFaultClearRequired=true;",
        "  constant Boolean failedStartRollbackRequired=true;",
        "  constant Boolean heaterPermissionFeedbackRequired=true;",
        "  constant Boolean implicitRestartForbidden=true;",
        f"  constant Real heaterPowerLimitByState[{len(states)}]={{{','.join(real(process['power']['heater_peak_cap_w'][state]) for state in states)}}};",
        f'  constant String crossSolverState="{process["release"]["cross_solver_state"]}";',
        f"  constant String powerPhaseNames[{len(phase_names)}]={{{','.join(chr(34) + n + chr(34) for n in phase_names)}}};",
        f"  constant Real phaseAverage[{len(phase_names)}]={{{','.join(real(process['power']['phases'][n]['average_w']) for n in phase_names)}}};",
        f"  constant Real phasePeak[{len(phase_names)}]={{{','.join(real(process['power']['phases'][n]['peak_w']) for n in phase_names)}}};",
        "end GeneratedControl;",
    ]
    MODELICA_PATH.write_text("\n".join(lines) + "\n")
    print(f"CONTRACT_ARTIFACTS_OK revision={process['revision']} states={len(states)} faults={len(fault_reasons) - 1}")


if __name__ == "__main__":
    main()
