#!/usr/bin/env python3
"""CAD 기준선과 제어 계약에서 Arduino 제어 상수를 생성한다."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE_PATH = ROOT / "cad" / "parameters" / "baseline.json"
CONTRACT_PATH = ROOT / "control" / "process_contract.json"
FAULT_CONTRACT_PATH = ROOT / "control" / "fault_response_contract.json"
OUT = Path(__file__).resolve().parent / "src" / "generated_profiles.h"


def f(value: float) -> str:
    text = f"{float(value):.6g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def main() -> None:
    raw = BASELINE_PATH.read_bytes()
    baseline = json.loads(raw)
    contract_raw = CONTRACT_PATH.read_bytes()
    contract = json.loads(contract_raw)
    fault_contract_raw = FAULT_CONTRACT_PATH.read_bytes()
    fault_contract = json.loads(fault_contract_raw)
    shredder = baseline["shredder"]
    extruder = baseline["extruder"]
    profiles = baseline["profiles"]
    calibration = shredder["motor"]["reference_calibration"]
    if contract["revision"] != fault_contract["revision"]:
        raise SystemExit("process/fault-response contract revision mismatch")
    states = list(contract["states"])
    material_states = contract["material_session"]["states"]
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.",
        f'constexpr const char* CONFIG_REVISION = "{contract["revision"]}";',
        f'constexpr const char* CONFIG_BASELINE_SHA256 = "{hashlib.sha256(raw).hexdigest()}";',
        f'constexpr const char* PROCESS_CONTRACT_SHA256 = "{hashlib.sha256(contract_raw).hexdigest()}";',
        f'constexpr const char* FAULT_RESPONSE_CONTRACT_SHA256 = "{hashlib.sha256(fault_contract_raw).hexdigest()}";',
        "enum class MachineState : uint8_t { " + ", ".join(states) + " };",
        "enum class MaterialSession : uint8_t { " + ", ".join(material_states) + " };",
        "struct StatePermissions { bool shredder, screw, process_heaters, feeder, puller, spooler, traverse, cooling; };",
        "struct PhasePower { float average_w, peak_w; };",
        "constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{",
        f"    {f(calibration['no_load_current_a'])}, {f(calibration['torque_per_amp_nm'])},",
        f"    {f(calibration['motor_to_cutter_ratio'])}, {f(calibration['drivetrain_efficiency'])},",
        f"    {f(calibration['max_continuous_current_a'])}, {f(calibration['max_peak_current_a'])},",
        f"    {f(calibration['no_load_rpm'])}, {f(calibration['thermal_limit_c'])}, false}};",
    ]
    for material, enum_name, maintenance in [
        ("PLA", "PLA", 45),
        ("PET", "PET", 60),
    ]:
        p = profiles[material]
        control = contract["materials"][material]
        t = shredder["material_torque_limits_nm"][material]
        zones = extruder[f"{material.lower()}_zone_c"]
        die = extruder[f"{material.lower()}_die_c"]
        purge = 80 if material == "PLA" else 120
        lines += [
            f"constexpr ProcessProfile {material}_PROFILE{{",
            f"    MaterialProfile::{enum_name}, {int(shredder[f'{material.lower()}_rpm'])}, {f(t['continuous'])}, {f(t['jam'])},",
            f"    {int(control['overload_dwell_ms'])}, {int(control['reverse_ms'])}, {int(contract['jam']['maximum_retries'])}, {maintenance}, false, 0, 0,",
            f"    {f(p['feeder_rpm'])}, {f(p['screw_rpm'])},",
            f"    {{{int(zones[0])}, {int(zones[1])}, {int(zones[2])}}}, {int(die)}, {int(p['fan_percent'])},",
            f"    {f(p['puller_feedforward_mm_s'])}, {f(p['kp'])}, {f(p['ki'])}, {purge}}};",
        ]
    lines += [
        f"constexpr float INPUT_MECHANICAL_FUSE_NM = {f(shredder['mechanical_relief_torque_nm'])};",
        f"constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = {f(shredder['phase_drivetrain_allowable_torque_nm'])};",
        f"constexpr float SHAFT_CUTTER_ALLOWABLE_NM = {f(shredder['shaft_cutter_allowable_torque_nm'])};",
        f"constexpr uint16_t JAM_STARTUP_GRACE_MS = {int(contract['jam']['startup_grace_ms'])};",
        f"constexpr float JAM_RPM_DEFICIT_RATIO = {f(contract['jam']['rpm_deficit_ratio'])};",
        f"constexpr float JAM_CURRENT_SENSOR_SATURATION_A = {f(contract['jam']['current_sensor_saturation_a'])};",
        f"constexpr uint16_t JAM_STOP_MS = {int(contract['jam']['stop_ms'])};",
        f"constexpr float PLA_SHREDDER_DUTY_BIAS = {f(contract['materials']['PLA']['shredder_duty_bias'])};",
        f"constexpr float PLA_SHREDDER_SPEED_KP = {f(contract['materials']['PLA']['shredder_speed_kp'])};",
        f"constexpr float PET_SHREDDER_DUTY_BIAS = {f(contract['materials']['PET']['shredder_duty_bias'])};",
        f"constexpr float PET_SHREDDER_SPEED_KP = {f(contract['materials']['PET']['shredder_speed_kp'])};",
        f"constexpr float SHREDDER_MEASUREMENT_FILTER_S = {f(contract['shredder_speed_control']['measurement_filter_s'])};",
        f"constexpr float NORMAL_PHASE_PEAK_LIMIT_W = {f(contract['power']['normal_phase_peak_limit_w'])};",
        f"constexpr float PSU_RATING_W = {f(contract['power']['psu_rating_w'])};",
        f"constexpr uint16_t HEATER_SAMPLE_PERIOD_MS = {int(contract['heater_control']['sample_period_ms'])};",
        f"constexpr uint16_t HEATER_WINDOW_MS = {int(contract['heater_control']['time_proportion_window_ms'])};",
        f"constexpr float HEATER_MIN_VALID_C = {f(contract['heater_control']['minimum_valid_c'])};",
        f"constexpr float HEATER_MAX_VALID_C = {f(contract['heater_control']['maximum_valid_c'])};",
        f"constexpr float HEATER_OVERTEMPERATURE_C = {f(contract['heater_control']['overtemperature_c'])};",
        f"constexpr uint32_t HEATER_NOT_HEATING_DWELL_MS = {int(contract['heater_control']['not_heating_dwell_ms'])}UL;",
        f"constexpr float HEATER_NOT_HEATING_MIN_RISE_C = {f(contract['heater_control']['not_heating_min_rise_c'])};",
        f"constexpr uint32_t HEATER_UNEXPECTED_RISE_DWELL_MS = {int(contract['heater_control']['unexpected_rise_dwell_ms'])}UL;",
        f"constexpr float HEATER_UNEXPECTED_RISE_C = {f(contract['heater_control']['unexpected_rise_c'])};",
        f"constexpr uint32_t FORMING_SCREW_RUNDOWN_MS = {int(fault_contract['timing']['screw_rundown_s'] * 1000)}UL;",
        f"constexpr uint32_t FORMING_PULLER_WASTE_MS = {int(fault_contract['timing']['puller_waste_s'] * 1000)}UL;",
        f"constexpr uint32_t PULLER_TACH_STARTUP_GRACE_MS = {int(fault_contract['timing']['puller_tach_startup_grace_s'] * 1000)}UL;",
        f"constexpr uint32_t THERMAL_HOLD_MS = {int(fault_contract['timing']['thermal_hold_s'] * 1000)}UL;",
        f"constexpr uint32_t PURGE_MINIMUM_MS = {int(contract['purge']['minimum_elapsed_s'] * 1000)}UL;",
        f"constexpr float PURGE_MINIMUM_SCREW_REVOLUTIONS = {f(contract['purge']['minimum_screw_revolutions'])};",
        f"constexpr float PURGE_SCREW_SCALE = {f(contract['purge']['screw_scale'])};",
        f"constexpr uint32_t REQUALIFICATION_STABLE_MS = {int(contract['requalification']['diameter_stable_duration_s'] * 1000)}UL;",
        f"constexpr uint32_t REQUALIFICATION_TRANSPORT_PLA_MS = {int(contract['requalification']['transport_delay_s']['PLA'] * 1000)}UL;",
        f"constexpr uint32_t REQUALIFICATION_TRANSPORT_PET_MS = {int(contract['requalification']['transport_delay_s']['PET'] * 1000)}UL;",
        f"constexpr uint8_t REQUALIFICATION_VALID_SAMPLES = {int(contract['requalification']['minimum_consecutive_valid_samples'])};",
        f"constexpr float REQUALIFICATION_U95_MAX_MM = {f(contract['requalification']['u95_max_mm'])};",
        f"constexpr float REQUALIFICATION_DIAMETER_ERROR_MAX_MM = {f(contract['requalification']['diameter_tolerance_mm'])};",
        f"constexpr float REQUALIFICATION_OVALITY_MAX_MM = {f(contract['requalification']['ovality_max_mm'])};",
        f"constexpr float DANCER_WARNING_RAD = {f(contract['dancer']['warning_rad'])};",
        f"constexpr float DANCER_CONTROLLED_STOP_RAD = {f(contract['dancer']['controlled_stop_rad'])};",
        f"constexpr float DANCER_MECHANICAL_HARD_STOP_RAD = {f(contract['dancer']['mechanical_hard_stop_rad'])};",
        f"constexpr uint8_t COOLING_COMMAND_THRESHOLD_PWM = {round(contract['cooling_feedback']['command_threshold_percent'] * 255 / 100)};",
        f"constexpr float COOLING_FEEDBACK_MIN_A = {f(contract['cooling_feedback']['healthy_current_window_a'][0])};",
        f"constexpr float COOLING_FEEDBACK_MAX_A = {f(contract['cooling_feedback']['healthy_current_window_a'][1])};",
        f"constexpr uint32_t COOLING_FEEDBACK_DWELL_MS = {int(contract['cooling_feedback']['fault_dwell_s'] * 1000)}UL;",
        f"constexpr uint32_t COOLING_STARTUP_HEALTHY_DWELL_MS = {int(contract['cooling_feedback']['startup_probe']['healthy_feedback_dwell_s'] * 1000)}UL;",
        f"constexpr uint32_t COOLING_STARTUP_PROBE_TIMEOUT_MS = {int(contract['cooling_feedback']['startup_probe']['timeout_s'] * 1000)}UL;",
        f"constexpr uint8_t PLA_COOLING_STARTUP_PROBE_PWM = {round(contract['cooling_feedback']['startup_probe']['command_percent_by_material']['PLA'] * 255 / 100)};",
        f"constexpr uint8_t PET_COOLING_STARTUP_PROBE_PWM = {round(contract['cooling_feedback']['startup_probe']['command_percent_by_material']['PET'] * 255 / 100)};",
        f"constexpr float COOLDOWN_SAFE_TEMPERATURE_C = {f(contract['cooldown_completion']['max_process_temperature_c'])};",
        "constexpr float STATE_HEATER_PEAK_CAP_W[] = {",
    ]
    for state in states:
        lines.append(f"    {f(contract['power']['heater_peak_cap_w'][state])}, // {state}")
    lines += [
        "};",
        "constexpr StatePermissions STATE_PERMISSIONS[] = {",
    ]
    for state, permissions in contract["states"].items():
        values = ", ".join("true" if permissions[key] else "false" for key in ("shredder", "screw", "process_heaters", "feeder", "puller", "spooler", "traverse", "cooling"))
        lines.append(f"    {{{values}}}, // {state}")
    lines += [
        "};",
        "constexpr PhasePower NORMAL_PHASE_POWER[] = {",
    ]
    for state in contract["power"]["phases"]:
        phase = contract["power"]["phases"][state]
        lines.append(f"    {{{f(phase['average_w'])}, {f(phase['peak_w'])}}}, // {state}")
    lines += [
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"FIRMWARE_CONFIG_SYNC_OK baseline={hashlib.sha256(raw).hexdigest()[:12]} contract={hashlib.sha256(contract_raw).hexdigest()[:12]}")


if __name__ == "__main__":
    main()
