#!/usr/bin/env python3
"""단일 process contract에서 Arduino/Modelica 제어 상수를 생성한다."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE_PATH = ROOT / "cad" / "parameters" / "baseline.json"
CONTRACT_PATH = ROOT / "control" / "process_contract.json"
OUT = Path(__file__).resolve().parent / "src" / "generated_profiles.h"
MODELICA_OUT = ROOT / "simulation" / "openmodelica" / "PLA_PET_Recycler" / "GeneratedControl.mo"


def f(value: float) -> str:
    text = f"{float(value):.6g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def main() -> None:
    raw = BASELINE_PATH.read_bytes()
    baseline = json.loads(raw)
    contract_raw = CONTRACT_PATH.read_bytes()
    contract = json.loads(contract_raw)
    if baseline["revision"] != contract["revision"]:
        raise SystemExit("baseline/process contract revision mismatch")
    shredder = baseline["shredder"]
    extruder = baseline["extruder"]
    profiles = baseline["profiles"]
    calibration = shredder["motor"]["reference_calibration"]
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.",
        f'constexpr const char* CONFIG_REVISION = "{baseline["revision"]}";',
        f'constexpr const char* CONFIG_BASELINE_SHA256 = "{hashlib.sha256(raw).hexdigest()}";',
        f'constexpr const char* PROCESS_CONTRACT_SHA256 = "{hashlib.sha256(contract_raw).hexdigest()}";',
        "enum class MachineState : uint8_t { IDLE, SHREDDING, PREHEATING, EXTRUSION, COOLDOWN, FAULT, ESTOP };",
        "enum class MaterialSession : uint8_t { CLEAN, PLA_ACTIVE, PET_ACTIVE, PURGE_REQUIRED, SCREEN_CLEAN_REQUIRED, HOPPER_CLEAN_REQUIRED, TEMPERATURE_TRANSITION_REQUIRED, FINAL_CONFIRM_REQUIRED };",
        "struct StatePermissions { bool shredder, screw, process_heaters, feeder, puller, spooler, cooling; };",
        "struct PhasePower { float average_w, peak_w; };",
        "constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{",
        f"    {f(calibration['no_load_current_a'])}, {f(calibration['torque_per_amp_nm'])},",
        f"    {f(calibration['motor_to_cutter_ratio'])}, {f(calibration['drivetrain_efficiency'])},",
        f"    {f(calibration['max_continuous_current_a'])}, {f(calibration['max_peak_current_a'])},",
        f"    {f(calibration['no_load_rpm'])}, {f(calibration['thermal_limit_c'])}, false}};",
    ]
    for material, enum_name, maintenance in [
        ("PLA", "PLA", 45),
        ("PET", "PET", 60),
    ]:
        p = profiles[material]
        control = contract["materials"][material]
        t = shredder["material_torque_limits_nm"][material]
        zones = extruder[f"{material.lower()}_zone_c"]
        die = extruder[f"{material.lower()}_die_c"]
        purge = 80 if material == "PLA" else 120
        lines += [
            f"constexpr ProcessProfile {material}_PROFILE{{",
            f"    MaterialProfile::{enum_name}, {int(shredder[f'{material.lower()}_rpm'])}, {f(t['continuous'])}, {f(t['jam'])},",
            f"    {int(control['overload_dwell_ms'])}, {int(control['reverse_ms'])}, {int(contract['jam']['maximum_retries'])}, {maintenance}, false, 0, 0,",
            f"    {f(p['feeder_rpm'])}, {f(p['screw_rpm'])},",
            f"    {{{int(zones[0])}, {int(zones[1])}, {int(zones[2])}}}, {int(die)}, {int(p['fan_percent'])},",
            f"    {f(p['puller_feedforward_mm_s'])}, {f(p['kp'])}, {f(p['ki'])}, {purge}}};",
        ]
    lines += [
        f"constexpr float INPUT_MECHANICAL_FUSE_NM = {f(shredder['mechanical_relief_torque_nm'])};",
        f"constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = {f(shredder['phase_drivetrain_allowable_torque_nm'])};",
        f"constexpr float SHAFT_CUTTER_ALLOWABLE_NM = {f(shredder['shaft_cutter_allowable_torque_nm'])};",
        f"constexpr uint16_t JAM_STARTUP_GRACE_MS = {int(contract['jam']['startup_grace_ms'])};",
        f"constexpr float JAM_RPM_DEFICIT_RATIO = {f(contract['jam']['rpm_deficit_ratio'])};",
        f"constexpr float JAM_CURRENT_SENSOR_SATURATION_A = {f(contract['jam']['current_sensor_saturation_a'])};",
        f"constexpr uint16_t JAM_STOP_MS = {int(contract['jam']['stop_ms'])};",
        f"constexpr float PLA_SHREDDER_DUTY_BIAS = {f(contract['materials']['PLA']['shredder_duty_bias'])};",
        f"constexpr float PLA_SHREDDER_SPEED_KP = {f(contract['materials']['PLA']['shredder_speed_kp'])};",
        f"constexpr float PET_SHREDDER_DUTY_BIAS = {f(contract['materials']['PET']['shredder_duty_bias'])};",
        f"constexpr float PET_SHREDDER_SPEED_KP = {f(contract['materials']['PET']['shredder_speed_kp'])};",
        f"constexpr float SHREDDER_MEASUREMENT_FILTER_S = {f(contract['shredder_speed_control']['measurement_filter_s'])};",
        f"constexpr float NORMAL_PHASE_PEAK_LIMIT_W = {f(contract['power']['normal_phase_peak_limit_w'])};",
        f"constexpr float PSU_RATING_W = {f(contract['power']['psu_rating_w'])};",
        f"constexpr uint16_t HEATER_SAMPLE_PERIOD_MS = {int(contract['heater_control']['sample_period_ms'])};",
        f"constexpr uint16_t HEATER_WINDOW_MS = {int(contract['heater_control']['time_proportion_window_ms'])};",
        f"constexpr float HEATER_MIN_VALID_C = {f(contract['heater_control']['minimum_valid_c'])};",
        f"constexpr float HEATER_MAX_VALID_C = {f(contract['heater_control']['maximum_valid_c'])};",
        f"constexpr float HEATER_OVERTEMPERATURE_C = {f(contract['heater_control']['overtemperature_c'])};",
        f"constexpr uint32_t HEATER_NOT_HEATING_DWELL_MS = {int(contract['heater_control']['not_heating_dwell_ms'])}UL;",
        f"constexpr float HEATER_NOT_HEATING_MIN_RISE_C = {f(contract['heater_control']['not_heating_min_rise_c'])};",
        f"constexpr uint32_t HEATER_UNEXPECTED_RISE_DWELL_MS = {int(contract['heater_control']['unexpected_rise_dwell_ms'])}UL;",
        f"constexpr float HEATER_UNEXPECTED_RISE_C = {f(contract['heater_control']['unexpected_rise_c'])};",
        "constexpr StatePermissions STATE_PERMISSIONS[] = {",
    ]
    for state, permissions in contract["states"].items():
        values = ", ".join("true" if permissions[key] else "false" for key in ("shredder", "screw", "process_heaters", "feeder", "puller", "spooler", "cooling"))
        lines.append(f"    {{{values}}}, // {state}")
    lines += [
        "};",
        "constexpr PhasePower NORMAL_PHASE_POWER[] = {",
    ]
    for state in ("SHREDDING", "PREHEATING", "EXTRUSION", "COOLDOWN"):
        phase = contract["power"]["phases"][state]
        lines.append(f"    {{{f(phase['average_w'])}, {f(phase['peak_w'])}}}, // {state}")
    lines += [
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    states = list(contract["states"])
    permission_rows = []
    for state in states:
        p = contract["states"][state]
        permission_rows.append(",".join("true" if p[k] else "false" for k in ("shredder", "screw", "process_heaters", "feeder", "puller", "spooler", "cooling")))
    modelica = [
        "within PLA_PET_Recycler;",
        "package GeneratedControl",
        "  // AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.",
        f'  constant String revision="{contract["revision"]}";',
        f'  constant String contractSha256="{hashlib.sha256(contract_raw).hexdigest()}";',
    ]
    modelica += [f"  constant Integer {name}={index};" for index, name in enumerate(states, 1)]
    material_states = contract["material_session"]["states"]
    modelica += [f"  constant Integer MATERIAL_{name}={index};" for index, name in enumerate(material_states, 1)]
    modelica += [
        f"  constant Boolean permissions[{len(states)},7]=[{';'.join(permission_rows)}];",
        f"  constant Real jamStartupGrace={contract['jam']['startup_grace_ms']/1000:.6g};",
        f"  constant Real jamRPMDeficitRatio={contract['jam']['rpm_deficit_ratio']:.6g};",
        f"  constant Real jamCurrentSensorSaturation={contract['jam']['current_sensor_saturation_a']:.6g};",
        f"  constant Real jamTripTorque={contract['jam']['jam_trip_torque_nm']:.6g};",
        f"  constant Real driveNoLoadCurrent={calibration['no_load_current_a']:.6g};",
        f"  constant Real driveTorquePerAmp={calibration['torque_per_amp_nm']:.6g};",
        f"  constant Real driveMotorToCutterRatio={calibration['motor_to_cutter_ratio']:.6g};",
        f"  constant Real driveEfficiency={calibration['drivetrain_efficiency']:.6g};",
        f"  constant Integer maximumRetries={contract['jam']['maximum_retries']};",
        f"  constant Real shredderDutyLimit={contract['shredder_speed_control']['duty_limit']:.6g};",
        f"  constant Real shredderCommandFilter={contract['shredder_speed_control']['command_filter_s']:.6g};",
        f"  constant Real shredderMeasurementFilter={contract['shredder_speed_control']['measurement_filter_s']:.6g};",
        "  constant Real shredderDutyBiasByMaterial[2]={" + ",".join(f"{contract['materials'][s]['shredder_duty_bias']:.6g}" for s in ("PLA", "PET")) + "};",
        "  constant Real shredderSpeedKpByMaterial[2]={" + ",".join(f"{contract['materials'][s]['shredder_speed_kp']:.6g}" for s in ("PLA", "PET")) + "};",
        f"  constant Real normalPhasePeakLimit={contract['power']['normal_phase_peak_limit_w']:.6g};",
        f"  constant Real psuRating={contract['power']['psu_rating_w']:.6g};",
        f"  constant String crossSolverState=\"{contract['release']['cross_solver_state']}\";",
        "  constant Real phaseAverage[4]={" + ",".join(f"{contract['power']['phases'][s]['average_w']:.6g}" for s in ("SHREDDING", "PREHEATING", "EXTRUSION", "COOLDOWN")) + "};",
        "  constant Real phasePeak[4]={" + ",".join(f"{contract['power']['phases'][s]['peak_w']:.6g}" for s in ("SHREDDING", "PREHEATING", "EXTRUSION", "COOLDOWN")) + "};",
        "end GeneratedControl;",
        "",
    ]
    MODELICA_OUT.write_text("\n".join(modelica))
    print(f"FIRMWARE_CONFIG_SYNC_OK baseline={hashlib.sha256(raw).hexdigest()[:12]} contract={hashlib.sha256(contract_raw).hexdigest()[:12]}")


if __name__ == "__main__":
    main()
