#!/usr/bin/env python3
"""baseline.json에서 Arduino process profile 단일 source header를 생성한다."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE_PATH = ROOT / "cad" / "parameters" / "baseline.json"
OUT = Path(__file__).resolve().parent / "src" / "generated_profiles.h"


def f(value: float) -> str:
    text = f"{float(value):.6g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def main() -> None:
    raw = BASELINE_PATH.read_bytes()
    baseline = json.loads(raw)
    shredder = baseline["shredder"]
    extruder = baseline["extruder"]
    profiles = baseline["profiles"]
    calibration = shredder["motor"]["reference_calibration"]
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by firmware/arduino_mega/generate_config.py; do not edit.",
        f'constexpr const char* CONFIG_REVISION = "{baseline["revision"]}";',
        f'constexpr const char* CONFIG_BASELINE_SHA256 = "{hashlib.sha256(raw).hexdigest()}";',
        "constexpr DriveCalibration REFERENCE_DRIVE_CALIBRATION{",
        f"    {f(calibration['no_load_current_a'])}, {f(calibration['torque_per_amp_nm'])},",
        f"    {f(calibration['motor_to_cutter_ratio'])}, {f(calibration['drivetrain_efficiency'])},",
        f"    {f(calibration['max_continuous_current_a'])}, {f(calibration['max_peak_current_a'])},",
        f"    {f(calibration['no_load_rpm'])}, {f(calibration['thermal_limit_c'])}, false}};",
    ]
    for material, enum_name, maintenance, overload, reverse in [
        ("PLA", "PLA", 45, 650, 800),
        ("PET", "PET", 60, 850, 1100),
    ]:
        p = profiles[material]
        t = shredder["material_torque_limits_nm"][material]
        zones = extruder[f"{material.lower()}_zone_c"]
        die = extruder[f"{material.lower()}_die_c"]
        purge = 80 if material == "PLA" else 120
        lines += [
            f"constexpr ProcessProfile {material}_PROFILE{{",
            f"    MaterialProfile::{enum_name}, {int(shredder[f'{material.lower()}_rpm'])}, {f(t['continuous'])}, {f(t['jam'])},",
            f"    {overload}, {reverse}, {int(shredder['max_reverse_retries'])}, {maintenance}, false, 0, 0,",
            f"    {f(p['feeder_rpm'])}, {f(p['screw_rpm'])},",
            f"    {{{int(zones[0])}, {int(zones[1])}, {int(zones[2])}}}, {int(die)}, {int(p['fan_percent'])},",
            f"    {f(p['puller_feedforward_mm_s'])}, {f(p['kp'])}, {f(p['ki'])}, {purge}}};",
        ]
    lines += [
        f"constexpr float INPUT_MECHANICAL_FUSE_NM = {f(shredder['mechanical_relief_torque_nm'])};",
        f"constexpr float PHASE_DRIVETRAIN_ALLOWABLE_NM = {f(shredder['phase_drivetrain_allowable_torque_nm'])};",
        f"constexpr float SHAFT_CUTTER_ALLOWABLE_NM = {f(shredder['shaft_cutter_allowable_torque_nm'])};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"FIRMWARE_CONFIG_SYNC_OK sha256={hashlib.sha256(raw).hexdigest()[:12]}")


if __name__ == "__main__":
    main()
