M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-08-28T08:50:18+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-28T08:50:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-125.0
X185.0Y-5.0
X185.0Y-125.0
M30
