within PLA_PET_Recycler.Scenarios;
package V062ShadowScenarios
  model PullerTransientSaturation
    extends Systems.ActuationShadowSystem(pullerLoadFactor=12,pullerFaultStart=1,pullerFaultEnd=1.5);
  end PullerTransientSaturation;
  model PullerPersistentSaturation
    extends Systems.ActuationShadowSystem(pullerLoadFactor=12,pullerFaultStart=1,pullerFaultEnd=20);
  end PullerPersistentSaturation;
  model PullerTachLoss
    extends Systems.ActuationShadowSystem(pullerTachAvailable=false);
  end PullerTachLoss;
  model PullerSpeedLoopLoadStep
    extends Systems.ActuationShadowSystem(pullerLoadFactor=1.8,pullerFaultStart=3,pullerFaultEnd=6);
  end PullerSpeedLoopLoadStep;
  model SingleCoolingFanLoss
    extends Systems.ActuationShadowSystem(fan1Available=false);
  end SingleCoolingFanLoss;
  model DualCoolingFanLoss
    extends Systems.ActuationShadowSystem(fan1Available=false,fan2Available=false);
  end DualCoolingFanLoss;
  model CoolingFeedbackImplausible
    extends Systems.ActuationShadowSystem(coolingFeedbackWhileOff=true);
  end CoolingFeedbackImplausible;
  model DuctBlockageSensitivity
    extends Systems.ActuationShadowSystem(ductFlowFactor=0.35);
  end DuctBlockageSensitivity;
  model ScrewCommandNoMotion
    extends Systems.ActuationShadowSystem(screwMotionRatio=0);
  end ScrewCommandNoMotion;
  model ScrewCouplingSlip
    extends Systems.ActuationShadowSystem(screwMotionRatio=0.25);
  end ScrewCouplingSlip;
  model PurgeMeasuredRevolutionsLow
    extends Systems.ActuationShadowSystem(screwMotionRatio=0.5,purgeDuration=120);
  end PurgeMeasuredRevolutionsLow;
  model PurgeMeasuredRevolutionsPass
    extends Systems.ActuationShadowSystem(screwMotionRatio=1,purgeDuration=130);
  end PurgeMeasuredRevolutionsPass;
  model HeaterAllocatorAllZonesCold
    extends Systems.ActuationShadowSystem(heaterRequestPercent=100,heaterCapW=300);
  end HeaterAllocatorAllZonesCold;
  model HeaterAllocatorRecovery
    extends Systems.ActuationShadowSystem(heaterRequestPercent=70,heaterCapW=500);
  end HeaterAllocatorRecovery;
  model HeaterAppliedDutyAntiWindup
    extends Systems.ActuationShadowSystem(heaterRequestPercent=100,heaterCapW=180);
  end HeaterAppliedDutyAntiWindup;
  model SpoolRadiusSweep
    extends Systems.ActuationShadowSystem(spoolFill=1);
  end SpoolRadiusSweep;
  model DancerClosedLoopDisturbance
    extends Systems.ActuationShadowSystem(spoolFill=0.5);
  end DancerClosedLoopDisturbance;
  model SpoolJamBeforeControlledLimit
    extends Systems.ActuationShadowSystem(spoolJam=true);
  end SpoolJamBeforeControlledLimit;
  model TraversePitchEmptySpool
    extends Systems.ActuationShadowSystem(spoolFill=0);
  end TraversePitchEmptySpool;
  model TraversePitchFullSpool
    extends Systems.ActuationShadowSystem(spoolFill=1);
  end TraversePitchFullSpool;
  model TraverseLimitFailure
    extends Systems.ActuationShadowSystem(traverseLimitHealthy=false);
  end TraverseLimitFailure;
  model FormingChainFaultCascade
    extends Systems.ActuationShadowSystem(fan1Available=false);
  end FormingChainFaultCascade;
  model GaugeRequalificationToWaste
    extends Systems.ActuationShadowSystem(operatorRethread=false);
  end GaugeRequalificationToWaste;
  model ManualRethreadToProduction
    extends Systems.ActuationShadowSystem(operatorRethread=true);
  end ManualRethreadToProduction;
end V062ShadowScenarios;
